### PR TITLE
[#2676] Add tag-sensitive EOSC-Explore banner

### LINKED ISSUE #2676: Functionality for the IF demo in June
https://docs.google.com/document/d/1_haZYZYVTLReLBPCucDGY15lPbHXPjK1y3gyueVrQx4/edit#heading=h.7b420sv2xxte

tbd on Monday. Need to do it now. As a workaround for now:
as a workaround, we do accept that for the next release the banners for the 4 listed services are hardcoded

### PR DESCRIPTION
**Pull request by goreck888**
Replace "OpenAIRE-Explore" banner with
the "EOSC-Explore" one
The new banner is tag-sensitive
(it shows when a service has one
of the following:
```
["EOSC::Jupyter Notebook",
 "EOSC::Galaxy Workflow",
 "EOSC::Twitter Data"]
```
All configuration data is included in `docs/upgrade/3.38.0.md`

Closes #2676

### CODE REVIEW

**Comment by Marcelinna** [comment]
for all tag, text on banner should be "See Jupyter notebooks compatible with the **EGI Notebook** service at[ EOSC Explore ](https://explore.eosc-portal.eu/search/advanced/research-outcomes?f0=resultsubject&fv0=%22EOSC%3A%3ATwitter%20Data%22)(opens in a new window)"
image

**Comment by Marcelinna** [comment]
in Documentation 
```
```
The link can be constructed as below:
<baseURL>/services?tag=<url encoded tag> e.g.
https://marketplace.eosc-portal.eu/services?tag=EOSC::Jupyter+Notebook
Notice: there’s no difference if a space is encoded as `+` or as `%20`.
IMPORTANT: Tag must not be included in any parentheses like in the EOSC Explore example.
```

on PR 
-doesn't work /services?tag=EOSC::Jupyter+Notebook
- works /services?tag=EOSC%3A%3AJupyter%2BNotebook

**Comment by Marcelinna** [comment]
the banner should be visible for Egi Notebook if tag is different than above?
image

**Comment by Marcelinna** [comment]
image
When I click on the link on the banner I see
image

image
When I click on the link on the banner I see
image


image
When I click on the link on the banner I see
image

if the link on each banner is correct

**Comment by Marcelinna** [comment]
"EOSC::Twitter Data" - "eosc" is changed to lowercase
image

"EOSC::Galaxy Workflow"
image

"EOSC::Jupyter Notebook"
image

**Review by Marcelinna — APPROVED** [review]

**Review by kmarszalek — APPROVED** [review]

**Pull request merged**
