### PR TITLE
Service view redesigned

### PR DESCRIPTION
**Pull request by mkasztelnik**
Following elements were added/improved:
  * service logo can be added to the service
  * services list redesigned
  * service header redesigned
  * related service partial prototype using bootstrap cards

Screenshots from the current version:

services-list

service-show

service-related

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@wziajka after this is merged storage location can be configured using `STORAGE_DIR` env variable.

**Comment by roksanaer** [comment]
pr-262 or pr-263 redirects me to https://marketplace-1.docker-fid.grid.cyf-kr.edu.pl where i see no changes at all (there is even old top nav. bar)

Hovewer I have some comments relying on the screens:
- logo: OK
- service headers on the list: @abacz should they be so big?? and the font - is it the right one?
- "Available for SME within one day" is supposed to be replaced with "Dedicated for" from the service form. @abacz can you please change it in the mock up so it doesn't create confusion (right now we will not provide info how soon the service will be ready to use) - in a service entry and service box information about targeted users should be provided (field Dedicated for implemented by @kmarszalek, which is right now visible on the right side of a service entry and it should be removed from there.
- boxes for connected services: OK, great
- @mkasztelnik where is the placeholder for the service offer(s)?

**Comment by mkasztelnik** [comment]
@roksanaer service offers are shown only when there are offers :) It looks like that:

offers

For the styling, I did not change anything in css, only bootstrap classes are used. Fonts, h* sizes, etc. should be set globally (and I hoped it was done long time ago by @kosmidma with @abacz guidance...).

**Comment by roksanaer** [comment]
>service offers are shown only when there are offers :) 
makes sense ;)
>Fonts, h* sizes, etc. should be set globally (and I hoped it was done long time ago by @kosmidma with @abacz guidance...).
yeah, so @abacz add it for @kosmidma to fix :)

so it leaves us only to replace "Available for SME within one day" with "Dedicated for". thanks!

**Comment by abacz** [comment]
I've already add quick simple guidelines -> https://sketch.cloud/s/p8ljr/oeGA5j  This file will be updated constantly.

**Pull request merged**
