### PR TITLE
Help section with example accordion

### LINKED ISSUE #1158: HELP ( FAQ) page for MP
**Is your feature request related to a problem? Please describe.**

We don't have a place with questions/ answers for users. ( MP FAQs)

**Describe the solution you'd like**

- [x]  to create a separate Help page with a content 

The lay out as FAQs for Op. Portal :  https://eosc-portal.grid.cyfronet.pl/about/faqs

Link to Help page content : https://docs.google.com/document/d/1s283XLSdtgl9dhQs68OS0VwQnXwhUFsDrnAZscTmyzg/edit

- [ ]  to create a HELP in the footer under MP with a link to Help page

### PR DESCRIPTION
**Pull request by mkasztelnik**
This is an initial version for the help webpage. I used the first 2 bullets from faq and included them as an example. Right now accordion, headers look ugly and this is a field to explore by @jarekzet. 

Screenshot from 2019-11-13 19-47-03

Fixes #1158

### CODE REVIEW

**Comment by agpul** [comment]
Page location is OK, now I am waiting for the @jarekzet

**Comment by jarekzet** [comment]
Added light styling to FAQ's accordion as below: 
image

**Comment by mkasztelnik** [comment]
@MinLidia, @agpul  so now it is your turn to insert faq items to the webpage using template already prepared.

**Comment by mkasztelnik** [comment]
All help content was moved from Google Docs into the marketplace. 
  * @MinLidia please take a look into the help section. There are some inconsistences, different formatting, sometimes you are using `.` at the end of sentence otherwise not.
 * @jarekzet there is a problem with list styling. It seems like you globally set unstyled to all lists. Take a look at the help section and try to improve it. Use google doc as a reference for how it should look like.

**Pull request merged**
