### PR TITLE
[#879] Add "Clear search" functionality

### PR DESCRIPTION
**Pull request by bwilk**
Related to: https://github.com/cyfronet-fid/marketplace/issues/879
Implemented "Clear search" button

Zrzut ekranu 2019-06-17 o 13 27 38

### CODE REVIEW

**Comment by abacz** [comment]
I would rather implement view likes this https://app.zenhub.com/workspaces/cyfronet-fid-5b1e4b786c29461038c37df5/issues/cyfronet-fid/marketplace/879 where you have clear button in searchbar.

**Comment by bwilk** [comment]
Zrzut ekranu 2019-06-13 o 17 19 02

Ready for styling

**Comment by bwilk** [comment]
ahh sorry - wrong icon. You will probably feel more comfortable with `fa-times`

**Comment by agpul** [comment]
Would it be possible to hide "X" where there is nothing in the search bar? If no, I think that we can merge this PR because functionality is important.

**Comment by abacz** [comment]
Yes. This is a good idea.

**Comment by bwilk** [comment]
> Yes. This is a good idea.
Done

**Pull request merged**
