### PR TITLE
feat:[#3163] Add bundles to ordering_configuration

### LINKED ISSUE #3163: Add possibility to specify bundle from Configuration page
Acceptance criteria:
- [ ] As a Provider I would like to specify bundle from Configuration page

### PR DESCRIPTION
**Pull request by goreck888**
Add creating bundles to the
ordering_configuration panel
Fix parameters sending in offers
Closes #3163

### CODE REVIEW

**Review by Marcelinna — APPROVED** [review]

**Comment by eldenkat** [comment]
Change messages confirming actions:

1. Delete bundle - This action cannot be undone. Confirm to delete the Bundle.
2. Draft bundle - Save your progress without publishing. You can continue editing later.

**Review by Marcelinna — COMMENTED** [review]
image
When try draft bundle in configuration page

**Comment by eldenkat** [comment]
Adjust labels to avoid ovelapping:
Screenshot 2024-01-02 at 11 06 47

**Comment by eldenkat** [comment]
Adjust labels to avoid overlapping:
Screenshot 2024-01-02 at 11 06 47

**Comment by eldenkat** [comment]
"Unpublish bundle" on the configuration page redirects to the backoffice.

**Comment by eldenkat** [comment]
When trying to delete the bundle:
image

**Comment by eldenkat** [comment]
1. The Unpublish feature doesn't work.
2. Even though the related training has been removed, it is still visible in the bundle view and redirects to deleted site (www.google com)
Screenshot 2024-01-02 at 21 32 00     
Screenshot 2024-01-02 at 21 32 26
3. 
4.

**Comment by Marcelinna** [comment]
add a dot at the end 
image
image

**Comment by eldenkat** [comment]
Unpublish still doesn't work. Steps to reproduce:
1. Create bundle
2. Click edit -> unpublish
3. See - the status (label) is still set on "published"

**Comment by eldenkat** [comment]
Change button "Create Bundle"to "Publish Bundle"

**Review by eldenkat — APPROVED** [review]

**Pull request merged**
