### PR TITLE
[#1220] Show the offer access type on the offer view

### LINKED ISSUE #1220: Show the offer access type on the offer view
**Is your feature request related to a problem? Please describe.**

There is no description of the offer access type, so the user doesn’t know if the below offer is orderable externally/ internally, open. 

**Describe the solution you'd like**

Add the access type labels to the offers : 

 ***On the SERVICE PAGE with the offer selection*** : 

- [x] offers with Open Access - to show label "Open Access" 
- [x] offers with External ordering  -to show label "External ordering" 
- [x] offers with Internal ordering  - to show label "Internal ordering" 

 **on the O Step (offer selection) of SERVICE ACCESS WIZARD** 

- [x] offers with Open Access - to show label "Open Access" 
- [x] offers with External ordering  -to show label "External ordering" 
- [x] offers with Internal ordering  - to show label "Internal ordering"

### PR DESCRIPTION
**Pull request by goreck888**
Add offer type to the offer selection view
Add offer type to the project item view in projects

Fixes #1220

### CODE REVIEW

**Comment by goreck888** [comment]
@abacz please check the styling.

**Comment by jarekzet** [comment]
did some mods on badge styling: 
image

**Comment by MinLidia** [comment]
@jarekzet :  would you be able to have the same/ close to  Andrzej prototype : 

https://projects.invisionapp.com/share/V2QZE87N9S5#/screens/351955222_Item_List_Filters_Search

Would be better if we have the same  in the services and offers.

**Comment by jarekzet** [comment]
Made some mods to badge look: 
image

**Comment by jarekzet** [comment]
Added color fix for status badge: 
image

**Pull request merged**
