### PR TITLE
[#2267] Store query parameters by changing filters

### LINKED ISSUE #2267: Query, pagination and sorting parameters are not saved by changing other params
**Describe the bug**
Active Pagination, sort, query and filters parameters are deleted on request by changing another. It means if we have active filter and we enter something in query prompt and send the request, filters are deactivated. It applies to any other pair of listed parameters.

**To Reproduce**

1. Go to services.
2. Select two sci-domains for filtering (path: /services?scientific_domains[]=1&scientific_domains[]=26).
3. Change ordering, for example to "Z-A" (path: /services?scientific_domains[]=26&sort=-name). The filter is now only for a single sci-domain.
4. If you try to re-add it, then the ordering is cleared (path: /services?scientific_domains[]=1&scientific_domains[]=26).

**Expected behavior**
Filters, per_page and sort parameters are saved and changing parameters of one section has no influence on the other params

### PR DESCRIPTION
**Pull request by goreck888**
Query parameters, like filters were removed by changing
other params (text query, order of resources)
All parameters are saved now.
Fixes #2267

### CODE REVIEW

**Comment by Marcelinna** [comment]
I have such a case
1. Go to /services
2. Click on Filtr: Generic
3. Filter is turn on 
image
4. Click Arror - go backwards (Alt - left arrow)
5. Filter is turn on, but on left sidebar I see that Generic is selected still. 
image

**Comment by kmarszalek** [comment]
On this PR when i choose sort it doesnt add it to params.
Path:
-> Services -> Choose Filter -> Add Sorting by rating (doesn't add this to params) -> Choose 2 Filter -> web reloads and looses sorting.

**Review by kmarszalek — CHANGES_REQUESTED** [review]
it doesn't work as required. see comments above.

**Comment by Marcelinna** [comment]
Steps to reproduce
1. Add resource to comparison
2. Click on filtr (e.g) Scientific domain Generic
3. Click button "Compare" on comparison bar
4. See error
image

**Comment by Marcelinna** [comment]
Step to reproduce
1. Change sorting to by name Z-A
image
2. Write "a" in main searchbar
3. See error - 
Sort from "Z-A" is changing to "Best match"
image
4. Click "x" - deleted word from searchbar
5. See error -
Sort from "Best match" is changing to "A-Z"\
image

**Comment by Marcelinna** [comment]
Steps to reproduce
1. Go to /backoffice
2. Write "a" in main searchbar
image
3. Click enter or loup icon
4. See error - 
image

**Review by Marcelinna — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Review by kmarszalek — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
