### PR TITLE
Upgrade to ruby 3.0 and rails 6.1

### PR DESCRIPTION
**Pull request by jswk**
Closes: #2254.

commit:
[#2254] Upgrade ruby and rails to the latest versions

* Update Ruby to 3.0.2
* Update Rails to 6.1.4
* Change Unirest to Faraday
* Fix failing tests and deprecations

### CODE REVIEW

**Review by kmarszalek — APPROVED** [review]

**Review by wziajka — APPROVED** [review]

**Comment by Marcelinna** [comment]
There are no recommendations on this PR and I can't turn on them, does it matter?

**Comment by Marcelinna** [comment]
PR
image
beta
image

**Comment by Marcelinna** [comment]
beta
image
pr
image

**Comment by Marcelinna** [comment]
beta 
image

other pr
image

pr 2280
image

**Comment by Marcelinna** [comment]
except for a strange situation with errored status, everything looks ok

**Pull request merged**
