### PR TITLE
Change missed `service` to `resource` texts

### PR DESCRIPTION
**Pull request by goreck888**

### CODE REVIEW

**Review by agpul — CHANGES_REQUESTED** [review]
1.  image and dependend sites eg; https://marketplace.eosc-portal.eu/about_projects
2. Can you help me which modals did you change?

**Comment by agpul** [comment]
In this PR I am not able to add the resource to the project from the "project level". I am using this button:
image

And I've got:
image

**Comment by goreck888** [comment]
> In this PR I am not able to add the resource to the project from the "project level". I am using this button:
> image
> 
> And I've got:
> image
> 
> EDIT:
> In fact, I am not able to add the resource to the project at all:)

There's a problem with the database, we changed migration. Tests are ok.

**Review by agpul — APPROVED** [review]
I approve changes - we only need to remember about slugs and static pages (change from services to resources) after deployment.

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
