### PR TITLE
[#1895][#1896] Send user browser actions to recommender

### LINKED ISSUE #1895: Probe should trigger on Next / Previous page event navigation
Using browser's navigation buttons (or actions) should trigger probe user-action (see https://docs.cyfronet.pl/display/FID/Session+gathering). 

This issue might require some integration with turbolink, or using session storage, or some other methods.

As part of this issue research should be done how to best handle this case.

### PR DESCRIPTION
**Pull request by danielkryska**
Source PR #1910

- Handle open new tab/window actions on key and click combination
    - Handle open new tab/window action on click with the middle button
    - Handle open new tab/window (only inside of an app) by right click
    - Handle go back and forward with browser arrows #1895
    - Handle refresh page #1894
- fix visit_id [#45](https://github.com/cyfronet-fid/recommender-system/issues/45)
  - should be an 8-byte integer
  - source.visit_id should be the last user action target.visit_id
  - page_id should be taken from the last target
- field category_id should be renamed to categories in the body request to recommendations endpoint
- add information about the current commit hash/app version to the browser console log

Closes #1895, #1896, #1894, #1898, #45

### CODE REVIEW

**Comment by danielkryska** [comment]
Occurred bug not related to the scope

Steps to reproduce
1. Go to any service
2. Click the button `Access resource`
3. The button containing href to page '/offers', but force redirects to `/information`

What happened?
target.page_id is '/offers'

What should happen?
target.page_id should be '/information'

**Comment by danielkryska** [comment]
Inconsistent bug

Steps to reproduce
1. go to /services
2. click the search loop icon
3. click Access physical & eInfrastructures category

What happened?
page_id has query parameters

What should happen?
page_id shouldn't have query parameters

**Comment by danielkryska** [comment]
History and refresh some times doesn't send data to /user_actions

**Review by JanKapala — CHANGES_REQUESTED** [review]
# Invalid user actions chaining

### Description
In the chrome incognito mode, I went to `/services`(it is the first visit). Following recommendation request has been sent:

`recommendation`:

    {'timestamp': '2021-03-31T15:16:56.575+0200', 'unique_id': 1617396273, 'visit_id': 3234592889, 'page_id': '/service', 'panel_id': 'v1', 'search_data': {}, 'logged_user': False} 172.21.0.1 - - [31/Mar/2021 13:16:56] "POST /recommendations HTTP/1.1" 200 -


...and next I opened 3 recommended services - each of them in new tab (these are next 3 visits). I received following user actions:

`user_action_1`, `user_action_2`, `user_action_3`:

    {'timestamp': '2021-03-31T13:17:04.470Z', 'source': {'visit_id': 1617196623550, 'page_id': '/services', 'root': {'type': 'other'}}, 'target': {'visit_id': 1617197208785, 'page_id': '/services/identifiers-org-central-registry'}, 'action': {'type': 'browser action', 'text': '', 'order': False}, 'unique_id': 1617396273} 172.21.0.1 - - [31/Mar/2021 13:17:04] "POST /user_actions HTTP/1.1" 204 -
    {'timestamp': '2021-03-31T13:17:06.937Z', 'source': {'visit_id': 1617197208785, 'page_id': '/services/identifiers-org-central-registry', 'root': {'type': 'other'}}, 'target': {'visit_id': 1617197456655, 'page_id': '/services/seadatanet-doi-minting-service'}, 'action': {'type': 'browser action', 'text': '', 'order': False}, 'unique_id': 1617396273} 172.21.0.1 - - [31/Mar/2021 13:17:06] "POST /user_actions HTTP/1.1" 204 -
    {'timestamp': '2021-03-31T13:17:09.635Z', 'source': {'visit_id': 1617197456655, 'page_id': '/services/seadatanet-doi-minting-service', 'root': {'type': 'other'}}, 'target': {'visit_id': 1617197605128, 'page_id': '/services/pan-data'}, 'action': {'type': 'browser action', 'text': '', 'order': False}, 'unique_id': 1617396273} 172.21.0.1 - - [31/Mar/2021 13:17:09] "POST /user_actions HTTP/1.1" 204 -

Then, in the `/services/pan-data` page tab I clicked `details` (It's the fourth visit) and I went to '/services/pan-data/details' (in the same tab). I've received:

`user_action_4`:

    {'timestamp': '2021-03-31T13:23:44.987Z', 'source': {'visit_id': 1617197605128, 'page_id': '/services/pan-data', 'root': {'type': 'other'}}, 'target': {'visit_id': 1617198000480, 'page_id': '/services/pan-data/details'}, 'action': {'type': 'A', 'text': 'Details', 'order': False}, 'unique_id': 1617396273} 172.21.0.1 - - [31/Mar/2021 13:23:45] "POST /user_actions HTTP/1.1" 204 -

As we can see visit ids are chained in the wrong way - they (and related user actions) do not represent user journey in the portal - they are just chained linearly without taking into consideration openings in new tabs (what causes branching of the user journey tree).

Also page_ids are invalid - they has nothing to do with an actual user journey.

### Expected behaviour

visit_id of the recommendation request and visit_ids of each of 4 user actions should be related as follows:
user_action_1.source.visit_id == recommendation.visit_id
user_action_2.source.visit_id == recommendation.visit_id
user_action_3.source.visit_id == recommendation.visit_id
user_action_4.source.visit_id == user_action_3.target.visit_id

Similarily page_ids should be as follows:
user_action_1.source.page_id == recommendation.page_id
user_action_2.source.page_id == recommendation.page_id
user_action_3.source.page_id == recommendation.page_id
user_action_4.source.page_id == user_action_3.target.page_id

Then user actions and related visit_ids/page_ids should reflect following user journey:

Untitled Diagram (5)

As it was described multiple times in multiple places:

- [session gathering overview (probes, user actions, etc.)](https://docs.cyfronet.pl/pages/viewpage.action?spaceKey=FID&title=Session+gathering)
- [probes specification and placement](https://docs.cyfronet.pl/display/FID/Recommendation%27s+probe+placement+and+specification+in+MP)
- [review I (#1866)](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-616187649)
- [review II (#1866 - second time)](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-619660209)
- [review III (#1910)](https://github.com/cyfronet-fid/marketplace/pull/1910#pullrequestreview-623531577)
- [User action sending example](https://docs.cyfronet.pl/display/FID/User+actions+sent+during+user+journey+example)
- slack conversations
- online meetings

### Additional context
It's very sad it still doesn't work, especially knowing that the first document about user actions, user journey tree etc. (the first one in the list) has been published 4.02.2021 and it is 31.03.2021 today. (not to mention the architecture presentation at the beginning of the year when the overview of the user actions has been explained)

**Comment by danielkryska** [comment]
@JanKapala you're right in the case of `user journey tree etc. (the first one in the list) has been published 4.02.2021`. From then  API should be defined as the JSON object (with examples) and be static in time. As also you as the architect of the recommendation system and mentor of the project should write down all requirements of the probes system. By requirements, I mean a list of technical language-specific documentation (of features). I'm understanding that you may not know how it, so let me write them down for you as also for testers.

Probes should be gathered on actions like:
- user click on listed down elements in https://docs.cyfronet.pl/display/FID/Recommendation%27s+probe+placement+and+specification+in+MP
- user writing in the main catalog search (each letter trigger action - without debouncing)
- user history changes
- user page refresh

Example of JSON
```
{
  "user_id": 1,
  "unique_id": 1,
  "timestamp": "2021-03-30T10:49:10.958Z",
  "source": {
    "visit_id": 1000001,
    "page_id": "/services",
    "root": {
      "type": "recommendation_panel",
      "panel_id": "v1",
      "service_id": 1234
    }
  },
  "target": {
    "visit_id": 1000002,
    "page_id": "/services/some-service"
  },
  "action": {
    "type": "link",
    "text": "Service Name",
    "order": false
  }
}
```

Special requirements
**unique_id**
client identificator created from random 8 digits + timestamp of first user visit in browser, kept in a browser cookie

**source** 
user action context on-site A
**source.visit_id** 
- is gathered from the last user action **target.visit_id** from THE SAME TAB or from another tab only if the user opened a new one
- is an 8-byte digit
- is generated from adding unique browser tabID and timestamp of the action
**source.root** 
- mostly it's value is {type: 'other'}
- only in one case it has value as in the example below, its when user click recommended resource on /services page

```
{
      "type": "recommendation_panel",
      "panel_id": "v1",
      "service_id": 1234
    }

```

**target** 
context of where the user is going (to site B)
**target.visit_id**
- is an 8-byte digit
- is generated from adding unique browser tabID and timestamp of the action

**action**
context of action was made
**action.type** 
- it's DOM element tag (a, div, input, ...)
**action.text** 
- it's DOM element value
**action.order**
- mostly its value is `false`
- only in one case it has value `true`, its when the user 
1. go to any resource
2. click 'Access resource'
3. fill out all steps to 'Final step'
4. click 'Add to a project' <-- this trigger will send JSON body with **action.order** = `true`


Examples of data
- user click on recommended service
**source.root** is different

```
{
  "user_id": 1,
  "unique_id": 1,
  "timestamp": "2021-03-30T10:49:10.958Z",
  "source": {
    "visit_id": 1000001,
    "page_id": "/services",
    "root": {
      "type": "recommendation_panel",
      "panel_id": "v1",
      "service_id": 1234
    }
  },
  "target": {
    "visit_id": 1000002,
    "page_id": "/services/some-service"
  },
  "action": {
    "type": "link",
    "text": "Service Name",
    "order": false
  }
}
```

- user click on element other than recommended service
**source.root** is different

```
{
  "user_id": 1,
  "unique_id": 1,
  "timestamp": "2021-03-30T10:49:10.958Z",
  "source": {
    "visit_id": 1000001,
    "page_id": "/services",
    "root": {
      "type": "other"
    }
  },
  "target": {
    "visit_id": 1000002,
    "page_id": "/services/some-service"
  },
  "action": {
    "type": "link",
    "text": "Service Name",
    "order": false
  }
}
```

- user click on `Add to a project btn` 
**action.order** is different (true)

```
{
  "user_id": 1,
  "unique_id": 1,
  "timestamp": "2021-03-30T10:49:10.958Z",
  "source": {
    "visit_id": 1000001,
    "page_id": "/services",
    "root": {
      "type": "other"
     }
  },
  "target": {
    "visit_id": 1000002,
    "page_id": "/services/some-service"
  },
  "action": {
    "type": "link",
    "text": "Service Name",
    "order": true
  }
}
```

**Comment by danielkryska** [comment]
@JanKapala I almost forget to ask you for something. Please if you think that there is something I haven't write down (mostly I mean specific requirements), write a comment below. We could gather all together and place it in Confluence to use of anybody.

**Review by JanKapala — APPROVED** [review]

**Comment by Marcelinna** [comment]
During testing, I see that every time I change categories or click the filter, the recommendations change, it's desired behavior?

**Comment by Marcelinna** [comment]
I know that it was reported, but I am not sure that the problem has been solved, so I am pasting it to remind you that the problem is still present in PR.
image

**Comment by Marcelinna** [comment]
Recommender take into consideration unpublished services, maybe shouldnt?
image
image

**Comment by Marcelinna** [comment]
Beta provider view
image


PR 
image

**Comment by JanKapala** [comment]
Recommender instance (connected to the MP PR instance) has been provided with the MP production database dump and trained on it. If someone is testing on the MP PR instance as logged user, even if there is an account of this user in the MP production DB, the id of user account in the PR database can be different (it is highly probable). In fact, the user account can be also created in PR instance database while logging via EGI. As a recommender "knows" only about the production data (as users id etc.) but not about newly created data in PR instance database (or not about users with changed ids), there is a possibility that it doesn't find some IDs (received in recommendation request from MP PR instance) in its (dumped) MP production database. Then, the expected behaviour is to sent random recommendations back.

This is exacly the situation [here](https://github.com/cyfronet-fid/marketplace/pull/1946#issuecomment-818603111) so it can be treated as expected behaviour

**Comment by Marcelinna** [comment]
Problem with source_id
Steps:
1. Go to "/services"
2. Click on "Compute" category
image
3. Click on the Selecting bar "Order Type"
image
4. Click on the Selecting bar "Resource availability"
image
5. See source id in step 4 is the same as in step 2. 

user action is send after click on the selecting bar? It shouldnt be send only after selecting a value?

**Comment by Marcelinna** [comment]
Problem with source_id
Steps:

1. Go to "/services"
2. Write "g" in main serach bar 
image
3. Write "a" in main search bar
image
4. Write "p" in main search bar
image
5. Click All resource bar
image
6. Click Networking 
image

image
7. See source_id is the same all the time

**Comment by Marcelinna** [comment]
User action is added to bredcrumbs, if user click on this area request is send to recomender. It isnt show in documentation. If I click many times every request have the same source_id.
image

**Comment by Marcelinna** [comment]
Problem with source_id ?

Steps:
1. Go to "/services"
2. Click Add to comparison (e.g EGI Cloud Compute)
image


3. Click Add to comparison (e.g EGI High-Throughput Compute)
image


4. Click Remove from comparison (e.g EGI Cloud Compute)
image

**Comment by Marcelinna** [comment]
Problem with source_id ?

Steps:

1. Go to "/services"
2. Click on the service (e.g EGI Cloud Compute)
image

3. Click the button "Add to comparison"
image

4. Click the button "Access to resource"
image

5. See source_id in Step 3 and 4 is the same.

**Comment by Marcelinna** [comment]
On the last step field order is undefined not false
image

**Comment by Marcelinna** [comment]
Problem with page_id ?

Steps:

1. Go to "/services"
2. Click on the one of offers  (e.g EGI Cloud Compute - General purpose)
3. url is https://marketplace-12.docker-fid.grid.cyf-kr.edu.pl/services/egi-cloud-compute#offer-1
image

**Comment by Marcelinna** [comment]
I add service to the project, but order field is still false
image

**Comment by Marcelinna** [comment]
Problem with page_id ?

Steps:

1. Go to "/services"
2. Click on service (e.g EGI Cloud Compute)
3. Select offer (e.g General purpose)
4. Click Button Next (page is /services/egi-cloud-compute/information)
obraz
5. Click FAQ link
obraz
6. Click Back arrow
obraz

7. See page_id in step 6 shouldnt be /help ?

**Comment by Marcelinna** [comment]
Lack of prob in Clear All button 
obraz

**Comment by Marcelinna** [comment]
Problem with source_id ?

Steps:

1. Go to "/services"
2. Click "Add to comparison button " (e.g EGI Cloud Compute)
obraz
3. Click button "Compare"
obraz
4. See source_id is the same in step 2 and 3

**Comment by Marcelinna** [comment]
Sometimes when I come back to /services, I notice that source_id is null
obraz

**Comment by Marcelinna** [comment]
Problem with page_id ?

Steps:

1. Go to "/services"
2. Click "Add to comparison" button (eg. for EGI Cloud Compute)
3. Click button "Compare"
obraz
4. Click Back arrow
obraz

5. See source page_id shouldn't be /comparison in step 4

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
