### PR TITLE
fix:[#3254] Fixes for offers feature

### LINKED ISSUE #3254: Fixes for predefined offers feature
- [x] add links to the helpdesk and provider's guide
- [x] gray out type/subtype if it is empty at the moment - ok
- [ ] add "other" to all categories

- [x] add descriptions of other order types ok
- [x] correct the button text on Own Ordering System ok

- [x] correct arrows in parameters
- [x] correct default parameters (units, etc.)

- [ ] Add popups when creating an offer
- [x] Add dashes to empty fields

### PR DESCRIPTION
**Pull request by goreck888**
Fixes:
- Disable and gray out empty choices fields
- Fix button tag to "Own Ordering System"
- Fix default parameters' units
- Add links to the provider's guide and helpdesk

Closes #3254

### CODE REVIEW

**Comment by Marcelinna** [comment]
Add dashes to empty fields - I dont see that it is done

image

**Comment by Marcelinna** [comment]
Change Data source to Data
image
image

**Comment by AlicjaSwierad** [comment]
Changes in Figma:
- Button next (always active)
- Dropdowns activate/add during selection
 - Edit buttons removed (summary page)
- Tooltips added to offer parameters

**Comment by Marcelinna** [comment]
Publish button is smaller than other 
image

**Comment by AlicjaSwierad** [comment]
- [ ] Add a link to the provider's guide in the providers section - https://marketplace.eosc-portal.eu/user_documentation
- [ ] Other category at the end of the list
- [ ] Change "Data sources" to "data"
- [ ] Dropdowns activate/add during selection (Starting with one dropdown, when the user selects one, more dropdowns will be added)
- [ ] add tooltips to offer parametes (step 3)
- [ ] remove "Learn More about Offer Parameters ->" (step 3)

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
for all category, I don't see subcategories 
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
