### PR TITLE
feat:[#3127] Add access type to the research products

### LINKED ISSUE #3127: Add "Access type" to the Pin to project functionality
Acceptance criteria:

- [ ] Add the "Access type" field to the Pinning details according to Figma

https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=2050-57653&mode=design&t=LS2pZZx4fcQVQsa2-4

### PR DESCRIPTION
**Pull request by goreck888**
Add best_access_rights to the research products table Displaying access type in details
Closes #3127

### CODE REVIEW

**Comment by jarekzet** [comment]
added CSS mods for access rights badge:

image

**Comment by Marcelinna** [comment]
@jarekzet Can you style here too ?
image

**Comment by Marcelinna** [comment]
other type than open access don't displayed correctly 
image

**Comment by agpul** [comment]
image
Change from service to resource and redirect to the all catalogs instead of services catalogue

**Comment by Marcelinna** [comment]
@goreck888 @jarekzet 
Problem with collapse button 
image

**Comment by Marcelinna** [comment]
@jarekzet @goreck888 
should redirected to all catalogs
image

**Comment by Marcelinna** [comment]
@agpul it this view, the button  "Add service to this project" be changed to "Add resource to this project"?
image

**Review by Marcelinna — APPROVED** [review]

**Review by wujuu — APPROVED** [review]

**Pull request merged**
