### PR TITLE
 [#2274] Virtual tour for new users

### PR DESCRIPTION
**Pull request by lukasz-korzeniowski**
Create a virtual tour for new users named `overview`.

Create a direct route to handle transitioning from the service list to a
concrete service.

Closes: #2274.

# How to test

Navigate to https://pr-2311.docker-fid.grid.cyf-kr.edu.pl?tour=overview and take the tour.

### CODE REVIEW

**Comment by Marcelinna** [comment]
image
@lukasz-korzeniowski maybe we should add something else here? it doesn't look good

**Comment by Marcelinna** [comment]
@lukasz-korzeniowski 
image
is the text in this modal properly formatted?

**Comment by Marcelinna** [comment]
@lukasz-korzeniowski why order type is not include in text?
image

**Comment by Marcelinna** [comment]
@jswk we dont want skip tour button here?
image

**Comment by kmarszalek** [comment]
@abacz isn't the font too small? :)

**Review by abacz — CHANGES_REQUESTED** [review]
1. Visual bug
Screenshot 2021-09-23 at 09 11 39

2. Switch font inside <p> to 14px in rem, same header
3. Modals don;t looking like here -> https://invis.io/JXOZKC8WMDU#/429999624_MyProfile_-_Tour_2 (e.g.line above buttons, buttons have not appropriate size - too big)
4. There is now information about steps to end (counter)
5. Moddal arrow has visible border
Screenshot 2021-09-23 at 09 18 56
6. We have designed <ul> list with yellow dot (please, use them)
Screenshot 2021-09-23 at 09 21 15
Here also something wrong with margins below list.
7. Remove grey border around circles

Screenshot 2021-09-23 at 09 23 03

**Comment by lukasz-korzeniowski** [comment]
It was skipped by wp10. I have added the order type now.

Łukasz Korzeniowski 

Akademickie Centrum Komputerowe

**Comment by lukasz-korzeniowski** [comment]
> @lukasz-korzeniowski
> image
> is the text in this modal properly formatted?

updated

**Comment by Marcelinna** [comment]
image

I will changed You can also filter resources based on the audience they serve to 

- target user
 or make space beetwen provider and this sentence. 

if I look at this element, it seems to me that Communities and infrastructures, Providers, Dedicated for are equal and should be bulleted in the same way

**Comment by lukasz-korzeniowski** [comment]
> image
> 
> I will changed You can also filter resources based on the audience they serve to
> 
> * target user
>   or make space beetwen providers and this sentence.
> 
> if I look at this element, it seems to me that Communities and infrastructures, Providers, Dedicated for are equal and should be bulleted in the same way

Bullet for infrastructures added.

**Comment by kmarszalek** [comment]
Should steps look like that, i dont know if it is good or not. 
- placement of the tour in relation to highlighted element of the page? 
- there was arrow between tour and active element. 
@abacz @jarekzet 

1st step:
Zrzut ekranu 2021-09-24 o 08 15 21

2nd step:
Zrzut ekranu 2021-09-24 o 08 15 49

3rd step
Zrzut ekranu 2021-09-24 o 08 16 13

4th step:
Zrzut ekranu 2021-09-24 o 08 16 29

5th step:
Zrzut ekranu 2021-09-24 o 08 17 06

6th step:
Zrzut ekranu 2021-09-24 o 08 17 34

7th step:
Zrzut ekranu 2021-09-24 o 08 18 17

8th step:
Zrzut ekranu 2021-09-24 o 08 18 33

9th step:
Zrzut ekranu 2021-09-24 o 08 19 00

10th step:
Zrzut ekranu 2021-09-24 o 08 19 24

11th step:
Zrzut ekranu 2021-09-24 o 08 19 50

**Comment by jarekzet** [comment]
All graphic tweaks ware added including tips offset between elements. Now it is dynamically calculated without using css hacks.

**Comment by Marcelinna** [comment]
@jswk 
Steps to reproduce
1. Go to https://marketplace-12.docker-fid.grid.cyf-kr.edu.pl/?tour=overview
2. Go to Congratulations! - last step
3. Click button Cancel and end tour or click outside the modal, url is https://marketplace-12.docker-fid.grid.cyf-kr.edu.pl/services/100-percent-it-trusted-cloud?tour=overview
4. Refresh - tour is appears

whether the parameter ?tour=overview should still be in the url??

**Comment by kmarszalek** [comment]
5th step is not easily visible. Can we change it somehow?@abacz @jarekzet @jswk

**Comment by jswk** [comment]
https://github.com/cyfronet-fid/marketplace/pull/2311#issuecomment-926471672. @Marcelinna, it's correct that the parameter should be cleared, but this is outside of the scope of this ticket. It is the activation strategy that needs to be corrected. Please open a separate ticket for that. I will look into it.

**Comment by Marcelinna** [comment]
@abacz @lukasz-korzeniowski maybe we can add some bold to keywords, how we made for other tour

other tour 
image
 
overview tour 
image
image
image

**Comment by jswk** [comment]
> 5th step is not easily visible. Can we change it somehow?@abacz @jarekzet @jswk

@kmarszalek: I changed its placement to `auto`, so that the problematic popup positions outside the highlighted element. It should improve contrast.

**Review by kmarszalek — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Review by abacz — APPROVED** [review]

**Pull request merged**
