### PR TITLE
[#1653] Tours implementation

### LINKED ISSUE #1653: Tutorial / Introductionary Tours
**Is your feature request related to a problem? Please describe.**
Tours should be displayed the first time the user is visiting given page

**Describe the solution you'd like**
`Shepherd.js` should be used to implement the tours. Backend should connect seen tours to the active user profile, if user is not logged in the seen tours should be stored in a cookie. If user logs in at some point the cookie should be read and seen routes should be set from that cookie (@bwilk - will this be alright?)

**Additional context**
There is a couple of previews and samples on docs / invision

### PR DESCRIPTION
**Pull request by martaswiatkowska**
ToDo
- TESTS
- redirect on "next"
- canClickTarget (why It doesn't work)
- add to TourHistory new field (browser_id), clean up null-false from the user. For storing information about all users not only about logged users

Closes #1653

### CODE REVIEW

**Comment by abacz** [comment]
My personal review ;)
1. Font to small. Set 1rem for content
2. More space between button / link (about 25px?)
Screenshot 2020-10-22 at 21 00 20

3.
Screenshot 2020-10-22 at 21 02 53
- More padding inside box - shepherd-content (addition 15px will be enough)
- I would align center the link
- I would write less and end after first sentence ;)( The main section of the resource presentation page highlights the most important information.). Same in the next tour boxes.

4.  In this step i can't see header. 
Screenshot 2020-10-22 at 20 55 01

**Review by agpul — APPROVED** [review]
From my point of view, both tours work and look fine. I found one typo: 
image
@wziajka confirmed that feedback that I left is saved in our database

**Comment by michal-szostak** [comment]
@agpul - @goreck888 is working on the last piece (recaptcha) after he finishes I'll fix all found typos and then do merge

**Comment by agpul** [comment]
Captcha works fine, the only remark I have is that there is no info about "error" if captcha is not selected (as far as I know it is a known issue)

**Pull request merged**
