### PR TITLE
2949 changes in bundels

### PR DESCRIPTION
**Pull request by jarekzet**
mods according to #2949

### CODE REVIEW

**Comment by Marcelinna** [comment]
@jarekzet lack of space
image

**Comment by Marcelinna** [comment]
@jarekzet 
lack of order type on bundle
image

**Comment by Marcelinna** [comment]
@jarekzet Problem with bundle when I click on Access service button and go to Offer selection page
PR
image
FIGMA
image

**Comment by Marcelinna** [comment]
lack of main offer on view (bundle should has 3 offers)
image

**Comment by agpul** [comment]
image

I've bundled 3 offers but I can see only 2 of them on the main view.

**Comment by aleksandrahojszyk** [comment]
Bundle in a view of an offer should not have type of an order 
Screenshot 2023-04-13 at 10 41 32
Screenshot 2023-04-13 at 10 44 01

Then the left column and right column with tehnical capabilities will be more aligned

**Comment by Marcelinna** [comment]
@goreck888 Add Changelog

**Review by Marcelinna — APPROVED** [review]

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
