### PR TITLE
offer card equal height

### PR DESCRIPTION
**Pull request by jarekzet**
This PR resolves issue #1789

### CODE REVIEW

**Comment by bwilk** [comment]
@goreck888 @kmarszalek please help @jarekzet to fix the tests in this PR

**Comment by kmarszalek** [comment]
resolved by re-running. should offers width be equal?

**Review by roksanaer — CHANGES_REQUESTED** [review]
Please rebase this PR to the master version. I am finding a major issue when testing: parameters introduced to the offer are not shown at all in the backoffice view:
image

image
 
Parameters are shown in the user view though:
image

 
Tested service is B2find

Master does not bear such a problem. 

Additionally, would it be possible to extend the description if there is still some space left in the tile? like here:
image

can we show more text instead of 'show more' link?

**Review by roksanaer — APPROVED** [review]
After some consultation. approval for the PR is granted

**Pull request merged**
