### PR TITLE
[#1865] Recommendation API adjustments

### PR DESCRIPTION
**Pull request by danielkryska**
IMPORTANT!!! In case of unique_id clean cookies store before testing data

---

- Update /recommendations and /user_actions endpoints body
  - unique_id is integer
  - timestamp is in UTC iso8601 format
  - visit_id is integer
  - logged_user appear always, not only for logged user
- Change filters placements from filters field to search_data in /user_actions
- Add probe job to queue configuration
- Change JS fetch body field from action to user_action to prevent overwriting by Ruby
- Fix double triggering of `Add comparison` in service details panel
- /recommendations endpoint body changes
  - Extend resource availability filter with regions
  - Extend tree structure like filters to send also child nodes
  - Fix response body parsing
- Improve recommender error handling #1889
- Services ids should be displayed in received order from outer service
- visit_ids in source and target will be always different
- service_id fields will be populated with correct data on recommendation service triggering
- Fix recommended services URLs params when category is selected - now user can select category and go to recommended service  #1897
- Add data-probe class attribute to breadcrumb navigation #1892
- Extend /recommendation body filters.category_id field with it's ancestors ids  #1898
- Fix error when user click on element other than recommended system and field panel_id is sent as 0 to user_action

### CODE REVIEW

**Comment by danielkryska** [comment]
- Breadcrumbs as it uses library to render will be labeled with data-probe attribute in next PR

**Review by JanKapala — CHANGES_REQUESTED** [review]
**Invalid recommended services order**
- **Description**: Recommended services are displayed in MP recommendation panel in different order than in the list sent by the recommender system.
- **Expected behaviour**: Order of services in the recommendation panel should be exactly the same as in the response sent by the recommender after request on the `/recommendations` endpoint.

**Invalid User action visit ids**
- **Description**: User actions’ `source.visit_id` and `target.visit_id` are incorrect (often they are exactly the same in the given user action).
- **Expected behaviour**: `visit_id` is (as described in the Recommender API) The unique identifier of a user presence on the page in the specific time. So, the user_action’s `source.visit_id` should represent the presence of the user on the user_action’s source page and the `target.visit_id` should be related to the presence of the user on the user_action’s target page. These are two different presences so they have to have different visit_ids. User actions are used for tracking user activity in the portal, so user actions’ source/target visit_ids have to make them able to be chained into user history tree (as described here: https://docs.cyfronet.pl/display/FID/Session+gathering)

**Invalid user_action.root.service_id value**
- **Description**: After clicking recommended service in the recommendation panel, probe sends user action with incorrect `root.service_id`: zero.
- **Expected behaviour**: root.service_id should be an ID of the clicked service.

**Incorrect user_action.root.service_id usage**
- **Description**: sending `service_id` in user_action.root when it’s type is `other`
- **Expected behaviour**: Fields `panel_id` and `service_id` should be populated only if the `user_action.root.type` is “recommendation_panel” (as described in the Recommender API).

**Comment by danielkryska** [comment]
Bugs were fixed, waiting for steps to reproduce

```
Incorrect user_action.root.service_id usage

Description: sending service_id in user_action.root when it’s type is other
Expected behaviour: Fields panel_id and service_id should be populated only if the user_action.root.type is “recommendation_panel” (as described in the Recommender API).

**Review by JanKapala — CHANGES_REQUESTED** [review]
Tested in two ways:
-   in normal chrome window after cookies cleaning
-   in separate chrome incognito windows
# Bugs
## For logged in user
### Redundant unique_id
-   **Description**: Unique_id of the logged in user is not empty. 
-   **Expected behaviour**: following API documentation: “unique_id - the unique identifier of the not logged user. Specified only if logged_user=False”.
-   **Steps to reproduce**: for the logged user:
	1.  Click recommended service name in the recommendation panel
   
### Invalid source.visit_id and target_visit_id of the same user_action
-   **Description**: visit_ids and unique_id are identical again, moreover they all are also identical with visit_ids and unique_id of the previous user_action.
-   **Expected behaviour**: source.visit_id i target.visit_id of the same user_action should be different and they should be also different from unique_id. Each visit on the page should correspond to unique visit_id and user actions should have appropriate visit_id in their sources and targets, as described [here](https://docs.cyfronet.pl/display/FID/Session+gathering) and [here](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-616187649)
-   **Steps to reproduce**: for logged in user:
	1.   Click recommended service name in the recommendation panel
	2.   On the next page click service details

Example for two above bugs:
**Enqueued user_action 1 in MP:**

    **10:53:19 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 1755fcab-a8a3-4eca-a84d-c3156b32cfca) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T09:53:19.775Z\",\"source\":{\"visit_id\":1616798682,\"page_id\":\"/services\",\"root\":{\"type\":\"recommendation_panel\",\"service_id\":57,\"panel_id\":\"v1\"}},\"target\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3?from_recommendation_panel=true\"},\"action\":{\"type\":\"A\",\"text\":\"Elastic Cloud Compute Clust...\",\"order\":false},\"logged_user\":true,\"user_id\":1825,\"unique_id\":1616798682}"**

**Enqueued user_action2 in MP:**

    **11:05:01 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 349d2126-01b8-47f5-9924-956cddc944d8) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:05:01.762Z\",\"source\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3\",\"root\":{\"type\":\"other\"}},\"target\":{\"visit_id\":1616798682,\"page_id\":\"/services/elastic-cloud-compute-cluster-ec3/details\"},\"action\":{\"type\":\"A\",\"text\":\"Details\",\"order\":false},\"logged_user\":true,\"user_id\":1825,\"unique_id\":1616798682}"**

## For anonymous user
### Not related visit_ids make user_actions chaining impossible
-   **Description**: visit_ids of consecutive user_actions are not related
-   **Expected behaviour**: In user journey, two consecutive user actions (for example clicking recommended service and then clicking its details) should obey: user_action1.target.visit_id == user_action2.source.visit_id. They should can be chained into consistent user journey as described [here](https://docs.cyfronet.pl/display/FID/Session+gathering) and [here](https://github.com/cyfronet-fid/marketplace/pull/1866#pullrequestreview-616187649)
-   **Steps to reproduce**: for anonymous user:
	1. Click recommended service name in the recommendation panel
	2. On the next page click service details

Example for above bug:
**Enqueued user_action1 in MP:**

    **11:11:20 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: 59903b4c-6ef7-436b-b681-ae33a94a1640) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:11:20.117Z\",\"source\":{\"visit_id\":6380701618197596270,\"page_id\":\"/services\",\"root\":{\"type\":\"recommendation_panel\",\"service_id\":364,\"panel_id\":\"v2\"}},\"target\":{\"visit_id\":6380701618197596411,\"page_id\":\"/services/gbif-spain-collections-registry?from_recommendation_panel=true\"},\"action\":{\"type\":\"A\",\"text\":\"GBIF Spain Collections Registry\",\"order\":false},\"logged_user\":false,\"unique_id\":1616916152}"**

**Enqueued user_action2 in MP:**

    **11:12:54 web.1 | [ActiveJob] Enqueued Probes::ProbesJob (Job ID: f6102473-0658-4f49-980a-3b1715032125) to Sidekiq(probes) with arguments: "{\"timestamp\":\"2021-03-24T10:12:54.631Z\",\"source\":{\"visit_id\":6380701618197690784,\"page_id\":\"/services/gbif-spain-collections-registry\",\"root\":{\"type\":\"other\"}},\"target\":{\"visit_id\":6380701618197691003,\"page_id\":\"/services/gbif-spain-collections-registry/details\"},\"action\":{\"type\":\"A\",\"text\":\"Details\",\"order\":false},\"logged_user\":false,\"unique_id\":1616916152}"**

**Pull request merged**
