### PR TITLE
feat:[#3046] Add research products to the Projects

### PR DESCRIPTION
**Pull request by goreck888**
Add research products pinnable to the projects
Add models, controllers, and routes

How to test PR:
go to the new research_product_path
`/research_products/new`
with resource_id and resource_type params,
eg.
```
/research_products/new?resource_id=50|dedup_wf_001%3A%3A00e804d55fff4d449f2b105245992ae0&resource_type=software
/research_products/new?resource_id=50|06cdd3ff4700%3A%3A0d0916f71e57fc252109f47376a83194&resource_type=publication
```

then you can see an "add to the project" form
In the details, you can delete research_product
Closes https://github.com/cyfronet-fid/marketplace/issues/3046

Figma: https://www.figma.com/file/l6nViF0XSdT98of1VjJV9f/EOSC-Pin-the-Project?type=design&node-id=5-1639&mode=design&t=yjCOLQ4IXrROnODt-0

### CODE REVIEW

**Comment by Marcelinna** [comment]
When I click on the link I am redirected to the wrong place

image

**Comment by agpul** [comment]
> When I click on the link I am redirected to the wrong place
> 
> image

It should redirect to zenodo (1st URL). Wehn you expand this record you can choose different URLs (they should redirect to Zenodo)

**Comment by Marcelinna** [comment]
image

**Comment by agpul** [comment]
image
Change from Services to Resources

**Comment by Marcelinna** [comment]
When I try to add publication
image

I see an error page with MP 
image

**Comment by Marcelinna** [comment]
view when the user don't have a project
image

**Comment by Marcelinna** [comment]
View when the user doesn't have the project
image

**Comment by agpul** [comment]
Budal Store (https://explore.eosc-portal.eu/search/other?orpId=dedup_wf_001::00083cd1e843979fdda785dfb321dfad&return_path=search%2Fother&search_params=q%3D*%26standard%3Dtrue) has no links, in such cases add: @agpul

**Comment by Marcelinna** [comment]
image
1. Click Create New Project - nothing happened
2. Click Create New Project again - 
image

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
