### PR TITLE
New design for the bundle section

### PR DESCRIPTION
**Pull request by jarekzet**
New bundles styling

image

https://www.figma.com/file/QECjJQdDvFlYkqQZvFMulp/Services?type=design&node-id=105%3A6989&mode=design&t=SZHC5m1A3CvNHMle-1

### CODE REVIEW

**Comment by AlicjaSwierad** [comment]
- [ ] Styling: order required
- [ ] Change in button location, and order required

**Comment by jarekzet** [comment]
added styling changes: 
image

**Comment by AlicjaSwierad** [comment]
- [ ] add minimum spacing between the bundle heading and the order type label
image

- [ ] add styling to all order type labels
image

**Comment by Marcelinna** [comment]
@jarekzet @aleksandrahojszyk 
what view should there be in the case of more than 2 offers in the bundle
image

**Comment by AlicjaSwierad** [comment]
- [ ] change image in open access and fully open access label 
image

-add minimum spacing (24px) between the offer heading and the order type label
image

- [ ] align helpdesk to the offer (in the bundle)
image

**Comment by jarekzet** [comment]
added latest mods due to comments above:

image

**Comment by Marcelinna** [comment]
@goreck888 @wujuu please make a review and check the changelog

**Review by AlicjaSwierad — APPROVED** [review]

**Review by Michal-Kolomanski — APPROVED** [review]
Only styling. Test are the most important ✅

**Review by Marcelinna — APPROVED** [review]

**Pull request closed without merging**
