### PR TITLE
[HOTFIX] Fix number of resources in executive statistics

### PR DESCRIPTION
**Pull request by goreck888**

### CODE REVIEW

**Comment by Marcelinna** [comment]
image
image

**Comment by Marcelinna** [comment]
it is on PR ?
image

**Review by michal-szostak — APPROVED** [review]

**Comment by Marcelinna** [comment]
>     * [x]  dev QA
> 
>     * [ ]  tester QA
> 
> 
> it is ok on PR ?
> image

on PR number for Domains and Origins is stil 0

**Comment by goreck888** [comment]
>     * [x]  dev QA
> 
>     * [ ]  tester QA
> 
> 
> it is ok on PR ?
> image

It's ok, on PR instances we don't have resource orders.

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
