### PR TITLE
1068 improving start page

### PR DESCRIPTION
**Pull request by jarekzet**
added mods from #1068 + new mobile menu

### CODE REVIEW

**Comment by abacz** [comment]
@jarekzet
0. .home-anchor should disappear when achive #find-eosc
1. Align-middle menu button to logo
2. Set close RWD menu button at the same position as "hamburger" icon.
3. Use lighter close button (attachement).
[btn_close.svg.zip](https://github.com/cyfronet-fid/marketplace/files/3594582/btn_close.svg.zip)
4. Is it possible to apply right-left menu animation?
5. Switch tabs - noborder right-left
6. Carousel dots don't have white border inside :(
7. Can you set "drop behaviour" depend on screen resolution? (communities,providers, dedicated and learn more boxes). Example below.
drop-behaviour

Thx!

**Comment by abacz** [comment]
I also noticed that shadows are cutted.
shadow_cut

**Comment by bwilk** [comment]
@jarekzet may I ask you to add a brief description of your changes to the CHANGELOG.md ? 😄

**Comment by abacz** [comment]
@jarekzet We are almost there :P
1. Autocomplete border is visible. Especially on mobile view (<350).
Screenshot 2019-09-23 at 15 32 41

2. I am checking this PR online and there is a problem with tab. Nothing happened when I click on category tab. Is it works on your branch?

3. Could you add to this PR result of this task? (new logo) https://app.zenhub.com/workspaces/cyfronet-fid-5b1e4b786c29461038c37df5/issues/cyfronet-fid/marketplace/1107

4. Please, update branch :| (I know, sry)

Sorry for delay :(

**Pull request merged**
