### PR TITLE
2952 offer selection

### LINKED ISSUE #2952: Improve UI of the offer selection and access instruction steps
According to the Figma design:
- [ ] offer selection: https://www.figma.com/file/0FiUXGZWNtRVgzu9ide5fh/Bundle?node-id=772-26&t=iVsXKCrEw22faL8z-4
- [ ] access instruction: https://www.figma.com/file/0FiUXGZWNtRVgzu9ide5fh/Bundle?node-id=772-27&t=iVsXKCrEw22faL8z-4

### PR DESCRIPTION
**Pull request by jarekzet**
closes #2952

### CODE REVIEW

**Comment by Marcelinna** [comment]
image
Offer selection step - lack of main offer
image

**Comment by Marcelinna** [comment]
When I click on select bundle and go to Access instruction page 
image

**Review by goreck888 — APPROVED** [review]

**Comment by Marcelinna** [comment]
pr
image
master
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Create bundle 
1, Main offer 100-percent-it-trusted-cloud
2. Bundled offer b2find
3. Bundled offer Elastic Cloud Compute Cluster (EC3)

Go to Service b2find, Elastic Cloud Compute Cluster (EC3) and click button "Access the service"
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Lack main offer in /offer page
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
