### PR TITLE
[#2203] Fix the provider backoffice form

### PR DESCRIPTION
**Pull request by danielkryska**
- trim the form values before validation (issue nr 1)
- permit the attributes on provider update from params instead of current record (issue nr 2)

### CODE REVIEW

**Comment by Marcelinna** [comment]
link the issue for which this PR is

**Comment by Marcelinna** [comment]
- [ ] DEV
- [ ] QA

Logo is not required field - regression. 
according to earlier assumptions required fields in PC have to be required in MP, logo is one of them
[required fields in PC are not required in backoffice #1977](https://github.com/cyfronet-fid/marketplace/issues/1977)
[[#1977] Improve consistency between MP provider and PC provider #2078](https://github.com/cyfronet-fid/marketplace/pull/2078)

1. go to /backoffice/providers/
2. click the button "Add new provider"
4. Fill required field without logo, click the button "Create new provider" 
3. Provider is created, logo isnt required field.

**Comment by Marcelinna** [comment]
the solution must be implemented in each field, but it is not intended to remove the validation of it.
Still it is not possible to update fields for which the validation shows error 

- [ ] QA
- [ ] DEV

Step to reproduce for other example
1. Go to /backoffice/providers
2. Chose AUTHENIX
3. Click the button "Edit"
4. Go to "Other", change "Provider Upstream" to MP
5. Click button "Update Provider"
6. See error
image

7. Select the country for errored field
image

8. Click the button "Update Provider"
9. See error - Update isnt possible
image

**Review by michal-szostak — APPROVED** [review]

**Review by Marcelinna — CHANGES_REQUESTED** [review]
Steps to reproduce
1. Go to backoffice
2. Select Provider AGINFRA+
3. Click button "Edit"
4. Change upstream from PC to MP
5. Click button "Update Provider" - see error

**Comment by danielkryska** [comment]
> Steps to reproduce
> 
> 1. Go to backoffice
> 2. Select Provider AGINFRA+
> 3. Click button "Edit"
>    image
>    image
> 4. Change upstream from PC to MP
> 5. Click button "Update Provider" - see error Field for Public Contant and Admin is duplicated
>    image
>    image

done

**Review by goreck888 — COMMENTED** [review]
Everything is ok, but add changelog entry.

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
