### PR TITLE
[#3214] Add the new offer's form design

### PR DESCRIPTION
**Pull request by goreck888**
Split form into partials according
to the new design
For development purposes
all steps are visible in the single page

The wizard will be implemented after
rebase to the rails 7 branch

Figma:
https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=311%3A50733&mode=design&t=vgQslURJIfMdnagW-1

Excel:
https://docs.google.com/spreadsheets/d/1vUqLXRLJMUl60cpccloW45NdNrTawEOHY8YJ4vXfSYg/edit#gid=0

### CODE REVIEW

**Comment by AlicjaSwierad** [comment]
1. Change the link to Figma with the latest version
2. Add a pathway for modifying the offer
3. Modify the Own OMS popup - add a button for the helpdesk

**Comment by AlicjaSwierad** [comment]
Changes:
- adding information to the tooltip about the possibility of deleting the Service (https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=311%3A54543&mode=design&t=GYhsfButXs5YgiBx-1)
- removing the draft button from the offer edition flow
- change placeholder for summary (change to hint)

**Comment by AlicjaSwierad** [comment]
buttons:
- fully open access
- other
Added to figma

Tooltip changes in progress

**Comment by agpul** [comment]
First checkpoint 18.03:
- [ ] @wujuu fix Next button
- [ ] @goreck888 add active class neccessary to switch button in step 1 and 2
- [ ] @goreck888 add values from spreadsheet to category tree
- [ ] @goreck888 add predefined offer to step 3
- [ ] @goreck888 check step 2 with Figma properly
- [ ] @jarekzet style step 3 and 4, remove grey colour from category tree (step1)

**Comment by agpul** [comment]
Comments:
- [ ] @goreck888 dodać categorie na 3 poziomach wg excela
- [ ] @wujuu dodac inny widok w przypadku open access (i taki sam jest dla fully open access i dla other)
- [ ] @goreck888 wybrane parametry na kroku 3 jak w kroku 1 wybiore Compute, Stroage, Data, Training itp, jak wybiore Other  w korku 1 to w kroku 3 nie mam predefiniowane nic -> tylko przy tworzeniu
- [ ] @wujuu nie tworzy sie oferta przy dodwaniu serwisu (regresja do naprawy)
- [ ] @jarekzet dodaj podswietelnie na przycisku zamiast kropki

**Comment by Marcelinna** [comment]
Figma - User should have button Next disabled when required field arent filled
image

PR
image

**Comment by Marcelinna** [comment]
links doenst work
image

**Comment by Marcelinna** [comment]
@agpul 
lack of information for all types
image

**Comment by Marcelinna** [comment]
@agpul @goreck888 @wujuu 
Użytkownik jak teraz przejdzie do kroku wybory typy orderingu to defaultowo ma wybrany order required, na Figmie uzytkownik nie ma nic zaznaczone. Jesli ma byc cos defaultowo zaznaczone to chyba juz lepiej open access (pierwsza)
image
FIGMA
image

**Comment by Marcelinna** [comment]
When edit offer
image

**Comment by Marcelinna** [comment]
brak kreski gdy tagi sa puste
image

**Comment by Marcelinna** [comment]
@agpul @Karolina9824 @wujuu @goreck888 @AlicjaSwierad 
w przyszlości trzeba by było pomyśleć co jeśli nie ma wartości, czy pole nie powinno byc wyszarzone?
image

**Comment by Marcelinna** [comment]
Compute -> High-troughput Compute - > **Number of CPU cores per GPU core** added parameter should be deleted
image

**Comment by Marcelinna** [comment]
Compute -Cloud Compute, Cloud Container Compute, dont have **Other technical requirements** in default parametres
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
brak paramteru dla File storage
image

**Review by agpul — APPROVED** [review]

**Pull request merged**
