### PR TITLE
Marketplace layout mods

### PR DESCRIPTION
**Pull request by jarekzet**
Layout colors and fonts mods. Also removed box shadows and header color.

### CODE REVIEW

**Comment by agpul** [comment]
image
It looks bad...
@aleksandrahojszyk

**Comment by agpul** [comment]
image
We can't see the "My EOSC Marketplace"

**Comment by aleksandrahojszyk** [comment]
Zrzut ekranu 2022-11-25 o 10 31 01
kolor przycisku i background za Communitites i Infrastructures na kolor 3D4DB6

**Comment by eldenkat** [comment]
not an expert, but aren't there too many font sizes below?

**Comment by aleksandrahojszyk** [comment]
Zrzut ekranu 2022-11-25 o 11 06 04

**Comment by eldenkat** [comment]
too many shades of blue?

**Comment by aleksandrahojszyk** [comment]
Zrzut ekranu 2022-11-25 o 11 07 16
wszytskie UI elementy któ®e mamy żółte zmienić na 3D4DB6

**Comment by eldenkat** [comment]
after logging in, the word marketplace is white

**Comment by agpul** [comment]
> 

not a scope of this issue:)

**Comment by agpul** [comment]
>  

we may change but it is not a scope of this issue

**Comment by jarekzet** [comment]
All color/font/styling mods added in latest push.

**Comment by michal-szostak** [comment]
Code looks ok, I have one question - shouldn't `.alert` also be restyled? It does stand apart from the rest of the styles...

**Review by agpul — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Comment by Marcelinna** [comment]
@jarekzet can we improve this?
image

**Comment by Marcelinna** [comment]
when I hover on link, link is not visible @jarekzet @aleksandrahojszyk 
image

**Comment by Marcelinna** [comment]
Text is not visible @jarekzet @aleksandrahojszyk @agpul 
image

**Comment by Marcelinna** [comment]
Search bar is not visible 
@jarekzet @aleksandrahojszyk @agpul 
image

**Comment by jarekzet** [comment]
added latest mods: link hover colours, order page top bar background and size,

**Comment by agpul** [comment]
Alert is still green on many pages (only on the main page is light blue):
image

**Review by agpul — APPROVED** [review]

**Comment by Marcelinna** [comment]
"search interface shoudl be as link"
pr
image
production
image

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
