### PR TITLE
3269 visual adjustments

### LINKED ISSUE #3269: Visual adjustments for offers
Figma: 
https://www.figma.com/file/0F53l8h6P2Q7TpzLuFZ7qX/Offers%3A-Adding-and-Editing?type=design&node-id=516%3A55179&mode=design&t=jrj3zifEgwbknQcS-1

- [ ] Remove lines
image

- [ ] Change tooltip style (add) to URL restrictions
image

### PR DESCRIPTION
**Pull request by jarekzet**
Added styling mods
https://pr-3270.docker-fid.grid.cyf-kr.edu.pl

Closes #3269 

image

image

### CODE REVIEW

**Review by goreck888 — APPROVED** [review]

**Comment by AlicjaSwierad** [comment]
remove tooltip from "order required and EOSC OMS" 
image

Remove lines
image

**Comment by jarekzet** [comment]
edit offer header:
image

Summary lines color:

image

**Comment by AlicjaSwierad** [comment]
- [ ] information (fixed tooltip) "url should start with(...)" does not display when "ordered required" is selected
       (display when open access, fully open access, other is selected - next to the url input)

image

- [ ] Tooltips step 3 styling 
image
should be:
image

**Comment by Marcelinna** [comment]
Please @goreck888 @wujuu delete section about URL when ordering is EOSC OMS
image

**Comment by AlicjaSwierad** [comment]
@goreck888 

 information (fixed tooltip) "url should start with(...)" should not display when 'ordered required' is selected (display when open access, fully open access, or other is selected - next to the URL input).

**Review by Marcelinna — CHANGES_REQUESTED** [review]
.

**Pull request closed without merging**
