### PR TITLE
[#768] Issue hierarchy

### PR DESCRIPTION
**Pull request by michal-szostak**
## What is in this PR?

* Add support for issue hierarchy (master issue for project,
  sub issues for project items)

* Add rake migration task for existing projects / issues

## Questions and issues to discuss

* Race condition - sidekiq jobs can be run concurrently so that introduces potential to have duplicated project issues (chance is minimal, we have to discuss whether we accept that risk and do some clean up later or whether we should look for alternative approaches)
* Fields in epic issue do not conform to https://docs.cyfronet.pl/x/9xPDAg here is a summary:
  * `CP-ReasonForAccess` - does not exist in epic, but exist in subtask, in db we have reason for access for both `Project` and `ProjectItem`
  * `CP-ProjectInformation` - does not exist in epic
  * `CP-ScientificDiscipline` - does not exist in epic & also does not exist in `Project` (@goreck888 will create separate issue for this one)

Closes: #768

### CODE REVIEW

**Comment by agpul** [comment]
@michal-szostak thank you for fields that do not conform to docs, I will take them into the consideration during  preparing specification v2 (we will prepare this spec during project and affiliations rearrangement)

**Comment by bwilk** [comment]
Like discussed earlier we can live with the race condition for now. We should come back to refactoring as soon as we start implementation of the specialized JIRA connectivity service.

**Comment by agpul** [comment]
Fields were changed by Mal.

**Comment by michal-szostak** [comment]
I added `CP-ReasonForAccess` and `CP-ProjectInformation`. `CP-ScientificDiscipline` will be done in separate issue by @goreck888 as it requires DB migration and change in forms.

@agpul / @roksanaer - please check it out and if it's good we can merge it

**Pull request merged**
