### PR TITLE
3084 UI in adding to the projects

### LINKED ISSUE #3084: Rebuild UI in adding RP to the Projects
Figma: https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=424-4891&mode=design

https://www.figma.com/file/wFzD4qH6SwpfCybte3pLlb/EOSC-DRAFTS?type=design&node-id=1202-26229&mode=design

### PR DESCRIPTION
**Pull request by jarekzet**
closes #3084 

image

### CODE REVIEW

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/EOSC-Design?type=design&node-id=5118%3A2313&mode=design&t=1MjZuM3fOGNIoa8K-1 
please use it as a reference ( it is a quick sketch so the typography can be not the same but in development please use the styles you already have thank you )

**Comment by Marcelinna** [comment]
was this change intentional? I don't see it on FIGMA
image

**Comment by Marcelinna** [comment]
@aleksandrahojszyk @jarekzet shouldn't the text be more black?
image

**Comment by jarekzet** [comment]
> was this change intentional? I don't see it on FIGMA image

The tabs module is common element and the redesign applies also here. @aleksandrahojszyk do you want to leave new tabs here also?

**Comment by Marcelinna** [comment]
@jarekzet @aleksandrahojszyk Is the font too big?

pr
image


beta 
image

**Comment by Marcelinna** [comment]
shouldn't have the same style ?
image

**Comment by aleksandrahojszyk** [comment]
> > was this change intentional? I don't see it on FIGMA image
> 
> The tabs module is common element and the redesign applies also here. @aleksandrahojszyk do you want to leave new tabs here also?

Please keep it as it was before 
Screenshot 2023-10-04 at 11 13 57

**Comment by Marcelinna** [comment]
Add unpin button for research products
image

**Comment by aleksandrahojszyk** [comment]
https://www.figma.com/file/GKqwn5BIuvXg4YdLBsARIn/eosc?type=design&node-id=417%3A225&mode=design&t=XWxW65Ne2c3RijWl-1 
Ogólnie to w zakresie tego ticketu to miały być tylko zmienione te boxy i wygląd research produktów więc wrzucam poprawiony ekran –> wszystkie te wartości i wyglądy "dookoła" typu menu i ten górny panel z nazwa projektu ipt powinny zostać jak były a środek tylko zmieniony czyli reprezentacja research produktów oraz serwisów

**Comment by Marcelinna** [comment]
@jarekzet words are too close
image

**Comment by Marcelinna** [comment]
details resource product page
image
FIGAM
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
Why do I have Service again?
image

**Comment by Marcelinna** [comment]
Change UNPIN to Unpin
image

FIGMA
image

**Comment by Marcelinna** [comment]
Links not Links list
image

**Comment by Marcelinna** [comment]
delete alert window
image

**Review by Marcelinna — APPROVED** [review]

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
