### PR TITLE
[#560] Add service status to service

### LINKED ISSUE #560: Add service status in the MP back office
Service owner is allowed to decide wether his service is visible or accessible in the MP for the users.

Each service has status. For now the status can be:
draft
published

In the service description, service owner can decide if the service should be visible to users.

Enum set to published means that the service is visible in categories it's under and is findable with search functionalities. Enum set to draft: service in not visible or findable in the MP GUI
 but is visible and editable to the service user

for now published service is also editable

all current services should have published status

**Only 2 transitions are possible: draft -> published and published -> draft**

service transition publish -> draft makes all underpinned service offers a draft
draft -> publish service transition does not publish service offers. it would be useful to add adequate success info box:
Your service has been published! All offers connected to the service **did not** change their status. If you wish to publish your service offers, please go to the service offer panel and activate chosen offers.

### PR DESCRIPTION
**Pull request by martaswiatkowska**
Add status :draft and :published to services
Fix #560

### CODE REVIEW

**Comment by roksanaer** [comment]
3 questions:
* @martaswiatkowska @wziajka can somebody please add me an admin role so I can check this feature? 
* what are our next steps for this PR?
* @mkasztelnik @martaswiatkowska @bwilk @kmarszalek can you please conduct a review?

thanks

**Comment by wziajka** [comment]
@roksanaer  roles added.

**Comment by mkasztelnik** [comment]
This PR has 2 issues:
1. (Easy to fix) Service owner is able to change status using backoffice edit view
2. (Hard - to investigate) Counter cache for categories is wrong when service is created with draft state and next published. This is a problem of with the situation that service can belong to many categories (because of counter cache implementation located in `ServiceCategory` model which has no notification of service change).

To solve the second problem:
1. we need to "touch" all service `ServiceCategories` each time service status is changed
2. (to investigate) we need to check how `counter_culture` discovers changes and add "virtual" `state`  method there (most probably also `state_was`).

**Comment by mkasztelnik** [comment]
Problem with counter cache solved. This is ready for review.

**Comment by roksanaer** [comment]
i believe i need to be added a service owner role again? @wziajka i do not see the backoffice button after logging in:

obraz

**Comment by roksanaer** [comment]
published -> draft transition should be called “Stop showing in the Marketplace”

**Comment by mkasztelnik** [comment]
Maybe additional "retired" state?

śr., 16 sty 2019, 11:39: roksanaer <notifications@github.com> napisał(a):

**Comment by agpul** [comment]
As a service owner I can see only my services and I can't edit them and I believe it is OK, I would like to do the review as a SP Manager but I am waiting for proper role.

**Comment by agpul** [comment]
In my opinion we could be able to delete draft only if the service has never been published before. If we make a draft from service which was published (at least once) we could be able to retire this service or something, but not delete without any information about this service in a database. 
@roksanaer

**Comment by roksanaer** [comment]
The asaumption is good - deleting the draft is possible only in draft status. It is just the initial workflow and it will need upgrading. If test is fine - green light

**Pull request merged**
