### PR TITLE
Search by offers

### LINKED ISSUE #1387: Add the possibility to search by the service offers
**Is your feature request related to a problem? Please describe.**
Now when we type something in the search bar the result takes into consideration only service title and service description. We would like to add searching by the service offer.

**Describe the solution you'd like**
We would like to apply the solution proposed by @abacz here. 
1. Search: https://images.zenhubusercontent.com/5b4c669f624eef429c4400c8/05f8b4f1-cee7-4fce-a027-700d3a885b64
2. Search result (according to Andrzej):
-  One offer (not visible offer section)
If service has only one offer we shouldn't suggest in "offer" section (search).
-  More than one
When user click suggested offer we need to show him directly this on service page (href on the offer position)

**Additional context**
Additional information was discussed here: https://app.zenhub.com/workspaces/eosc-5b1e4b786c29461038c37df5/issues/cyfronet-fid/marketplace/793

**Visualization**
https://projects.invisionapp.com/share/NDW5PTX2S57#/screens/406787078_Item_List_Search_-_Offers
If one offer matches the text should be: The service has one offer that matches your search criteria
If service has more than one offer: The service has two/three/... offers that match your search criteria

### PR DESCRIPTION
**Pull request by martaswiatkowska**
Added offers to main search, 
Offers are listed in service box 

Fix #1387

### CODE REVIEW

**Comment by agpul** [comment]
@jarekzet can you improve UI on this PR?

**Comment by agpul** [comment]
I think that the service offer name should be more imp0ortant than service description, I type General purpose in the searchbar: 
image

**Comment by jarekzet** [comment]
Hi, wait until tomorrow with Margening. I will add some styling mods.

**Comment by martaswiatkowska** [comment]
OK

**Comment by agpul** [comment]
Now UI looks nice, but I found the additional problem. 
Why services aren't highlighted?
image
Offers highlight works fine:
image

**Comment by agpul** [comment]
OK, For me this PR is ready to merge

**Pull request merged**
