### PR TITLE
Update of the CHANGELOG for release 3.25.0

### PR DESCRIPTION
**Pull request by danielkryska**

### CODE REVIEW

**Review by goreck888 — APPROVED** [review]

**Review by kmarszalek — CHANGES_REQUESTED** [review]
update version in version file.

**Comment by danielkryska** [comment]
> update version in version file.

done

**Review by jswk — CHANGES_REQUESTED** [review]
Has 3.25.0-beta0 been approved?

**Comment by jswk** [comment]
I also don't see the commit with these changes in the `v3.25.x` branch yet. You should only forward merge a release branch once a non-beta release has been issued.

**Pull request closed without merging**
