### PR TITLE
[#2494] Fix InvalidRecommendationPanelIDError

### LINKED ISSUE #2494: InvalidRecommendationPanelIDError
Currently, on the production server, we get a lot of logs containing InvalidRecommendationPanelIDError.
The scope of this issue is to investigate the situation carefully and to fix the error.

### PR DESCRIPTION
**Pull request by Michal-Kolomanski**
Fixes #2494

### CODE REVIEW

**Comment by Marcelinna** [comment]
If we delete A/B test, bug "No possibility to start the v2 experiment for recommendations #2487" will be invalid and it should be close?

**Comment by Michal-Kolomanski** [comment]
> If we delete A/B test, bug "No possibility to start the v2 experiment for recommendations #2487" will be invalid and it should be close?

Yes. We are abandoning the v2 version entirely.

**Comment by Michal-Kolomanski** [comment]
I removed certain files, so please verify that there is no regression overall in MP @Marcelinna. Please remember that there is [second bug](https://github.com/cyfronet-fid/marketplace/issues/2495) so recommendations will not be always visible. Recommendations should be visible when using "Categories" or more than one "Scientific domains". I have tested this PR locally and recommendations were visible for me.

**Comment by jswk** [comment]
It looks good @Michal-Kolomanski.
Since we're scrapping the AB testing for now, then it would make sense to drop the line `gem "split", require: "split/dashboard"` from the Gemfile too. (You may see remaining places where it's used that way either, since execution will break on these.)

**Comment by Michal-Kolomanski** [comment]
> It looks good @Michal-Kolomanski. Since we're scrapping the AB testing for now, then it would make sense to drop the line `gem "split", require: "split/dashboard"` from the Gemfile too. (You may see remaining places where it's used that way either, since execution will break on these.)

Thank you for noticing. My new commit addresses your request.

**Review by jswk — COMMENTED** [review]
One more leftover I noticed: grep the project for the strings `ab_` and `AB `. There's yet several instances in the code, which don't lead to immediate failures, but could be pruned.
Sorry I didn't think of this earlier.

**Review by jswk — APPROVED** [review]
Looks good now. I don't see any more leftovers.

**Comment by Marcelinna** [comment]
we don't need a changelog for remove the a/b experiment from backoffice?

**Review by Marcelinna — APPROVED** [review]

**Comment by Michal-Kolomanski** [comment]
> we don't need a changelog for remove the a/b experiment from backoffice? something has changed for a user with admin privileges.

You are right. I have added those changes in the changelog.

**Pull request merged**
