### PR TITLE
faq page styling

### PR DESCRIPTION
**Pull request by jarekzet**
Added styling due to #3230 

image

### CODE REVIEW

**Comment by Marcelinna** [comment]
FIGMA - white background
image

PR
image

**Comment by Marcelinna** [comment]
@goreck888 @wujuu 
image

**Comment by jarekzet** [comment]
Added collapsed element styling mods:

image

**Comment by Marcelinna** [comment]
@jarekzet Can you make all box clickable similar to https://search.marketplace.eosc-portal.eu/asguide, becasue now I can click only in inscription
image

**Comment by jarekzet** [comment]
added active button width to 100%

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
