### PR TITLE
[#1805] Tour feedback view

### PR DESCRIPTION
**Pull request by goreck888**
Add tour feedback view in admin section

### CODE REVIEW

**Comment by bwilk** [comment]
@goreck888

1. Could you display 2/5 instead of 2 in the Rating field? 
1. Hint about possible value range would be also welcome (0-4)  
2. Maybe we should consider scale 1-5, * - *****, or even icons (https://fontawesome.com/icons/circle?style=solid) as it represents 1 - 5 dots (image attached)
image

**Comment by bwilk** [comment]
Also, can we display the timestamp of the rating??

**Comment by bwilk** [comment]
"Yes, I want to take part in the EOSC Portal design verification/validation" is represented as "Logged in user". Please change this to "Validation team t/f"

**Comment by bwilk** [comment]
Like that:
image

**Comment by roksanaer** [comment]
image

two issues that require change:
tour name does not say too much at the moment
I took the tour as a logged user and it was not logged in the tour feedback table.

**Comment by Marcelinna** [comment]
maybe the Tour name could be better presented than: service_details_intro, intro2 ?

**Review by wujuu — APPROVED** [review]

**Comment by goreck888** [comment]
> maybe the Tour name could be better presented than: service_details_intro, intro2 ? @roksanaer

It depends on developer which added the tour. I suggest better naming in future feature highlights, now leave as it is.

**Comment by goreck888** [comment]
> image
> 
> issue that require change:
> 
> I took the tour as a logged user and it was not logged in the tour feedback table.

Should working now.

**Comment by Marcelinna** [comment]
Tour feedback show mail despite user doesnt check the box. 

Steps to reproduce
1. Pass the tour
2. Fill fields in feedback tour modal
3. Check the box and write the email
image

4. Uncheck the box
image

5. Send the feedback

Expected behaviour:
In Admin panel _Contact Consent/Email_ is set as false

Actual result
image

**Comment by Marcelinna** [comment]
Sometime is problem with pass tour in "My profile" @goreck888 it will be new issue ?
below is a video with an error
https://www.awesomescreenshot.com/video/3061458?key=d46d6797bc55faf213ec8c31452cc89f

**Review by michal-szostak — APPROVED** [review]

**Comment by goreck888** [comment]
> Sometime is problem with pass tour in "My profile" @goreck888 @roksanaer it will be new issue ? this is a video with an error https://www.awesomescreenshot.com/video/3061458?key=d46d6797bc55faf213ec8c31452cc89f

I suppose it should be a new ticket.

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
