### PR TITLE
[#2727] Add catalogue specific links to PC

### LINKED ISSUE #2727: Manage the provider, Manage the resource for catalogue other than eosc
Admin of provider and resource can redirect to Provider Portal using buttons "Manage the provider", and "Manage the resource"
image

For Provider - When catalogue is other than "eosc" only link to the Provider dashboard should be visible
/dashboard/{catalogue.pid}/{provider.pid}/stats
image

For Resource - When catalogue is other than "eosc" only link to the Resource dashboard and Set parametres and offers should be visible
/dashboard/{catalogue.pid}/(provider.pid}/resource-dashboard/(resource.pid)/stats
image

### PR DESCRIPTION
**Pull request by goreck888**
Generate links to the Provider/Service dashboard
in PC depending on the catalogue
Fixes #2727

### CODE REVIEW

**Comment by Marcelinna** [comment]
When catalogue is other than eosc 
- Link to Edit Provider details
- Link to Edit Resource details 
- shouldn't be visible

image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Steps to reproduce

1. Go to PC and create provider and resources (by UI, catalogue eosc)
2. Go to the resource created by the PC page 
3. See problem 
image

**Review by Marcelinna — CHANGES_REQUESTED** [review]
above problem

**Comment by Marcelinna** [comment]
VERY IMPORTANT - need to import the catalogue on the production

**Review by danielkryska — APPROVED** [review]

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

After run import catalogue and update provider

beta
image
pr
image

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
