### PR TITLE
[#2768] Fix JMS for datasource

### PR DESCRIPTION
**Pull request by goreck888**

### CODE REVIEW

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
- Create datasource in PC (datasource has published status)
- See problem - datasource is not visible in MP

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Button - Manage datasource should be visible
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

1. Deactivate datasource in PC
2. See problem - in MP datasource has still status Published, should have status draft

image
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Step to reproduce
1. Delete datasource in PC
2. See problem - Datasource has published status in PC
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Please add resource organisation i Provider to datasources
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] Dev
When datasource is created JMS, Research Product Metadata is not visible
Please change Research Product Metadata to Research Product Metadata Licensing
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
- bundle exec rake import:datasources doesn't update datasource status 
In Api "active": ["false"], in MP datasource has published status, should has draty status

**Review by wziajka — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
