### PR TITLE
mp home page mods

### PR DESCRIPTION
**Pull request by jarekzet**
#2791 - mods of texts and link on home page

### CODE REVIEW

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Button Browse all services - should redirect to Services in SS
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Scientific domain and Category should redirect to SS

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Browse through catalogue should redirected to All catalogs

image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Browse through catalogue should redirected to All catalogs

image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Browse through catalogue should redirected to All catalogs

image

**Review by agpul — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
