### PR TITLE
links under search box fix

### PR DESCRIPTION
**Pull request by jarekzet**
Added mods according to #2980 

image

### CODE REVIEW

**Comment by Marcelinna** [comment]
Please add all catalogs
image

**Comment by jarekzet** [comment]
Added links and order according to the project:
image

**Comment by Marcelinna** [comment]
All catalog should redirect to 
https://beta.search.marketplace.eosc-portal.eu/search/all?q=*
image

because 
https://beta.search.marketplace.eosc-portal.eu/search/all-catalogs?q=*
return 0 result
image

**Comment by Marcelinna** [comment]
service bundle should redirect to /search/bundle

**Comment by jarekzet** [comment]
Added correct URLs for new tags

**Review by goreck888 — APPROVED** [review]

**Review by Marcelinna — APPROVED** [review]

**Pull request merged**
