### PR TITLE
[#2882] Add landing page

### PR DESCRIPTION
**Pull request by goreck888**
The page is available under /landing_page

### CODE REVIEW

**Comment by Marcelinna** [comment]
- [ ] QA
PR 
image
Figma
image

**Comment by Marcelinna** [comment]
- [ ] QA
PR
image
Figma
image

**Comment by Marcelinna** [comment]
@jarekzet can we improve this in smaill size
image

**Comment by Marcelinna** [comment]
- [ ] QA
the background color should be lighter so that the image does not stand out

image

**Comment by Marcelinna** [comment]
@agpul @aleksandrahojszyk for me Data management should be changed to Manage Research Data 
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
image

**Comment by Marcelinna** [comment]
- [ ] QA
When I hover on "Access training material" only the image is moved
When I hover on "Publish research outputs" the image and element below is moved too
image

**Comment by aleksandrahojszyk** [comment]
> @agpul @aleksandrahojszyk for me Data management should be changed to Manage Research Data image ![image](https://user-images.githubusercontent.com/59872096/219471463-7a1f4ccc-7238-4786-9695-055beb4f4a5b.png

Ma zostać Data Management, it's a thing dla researcherow i manage research data nie oddaje sensu

**Comment by agpul** [comment]
> > @agpul @aleksandrahojszyk for me Data management should be changed to Manage Research Data image
> > image
> 
> Ma zostać Data Management, it's a thing dla researcherow i manage research data nie oddaje sensu
> 
> @aleksandrahojszyk @agpul mi sie nie podoba ze to jedyny przyklad gdzie nazwa filtra sie nie zgadza w SS z tym co klikami

@aleksandrahojszyk rozumiam ze Data Management, zostalo ustalone na spokaniu? jesli tak msle ze trzeba zmienic lecz nie tu tlko w SS

**Comment by aleksandrahojszyk** [comment]
Racja, powinnismy to zmienić wszędzie

W dniu piątek, 17 lutego 2023 agpul ***@***.***> napisał(a):

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Please add dots to the sentences end. 

PR
image

**Comment by Marcelinna** [comment]
@goreck888 If someone type something in search bar should be redirected to link from env SEARCH_SERVICE_BASE_URL  too 
image

**Comment by Marcelinna** [comment]
Please add link My EOSC Dashboard https://eosc-user-dashboard.docker-fid.grid.cyf-kr.edu.pl/
image

**Pull request closed without merging**
