### PR TITLE
[#2908] Improve bundles email content

### LINKED ISSUE #2908: Improve bundles emails content
We need to provide new content to emails that are sent during bundles creation:

przy stworzeniu bundle'a:
%p Dear #{@bundled_offer.service.name} administrator,
%p Your offer #{offer_full_name(@bundled_offer)} was bundled in #{offer_full_name(@bundle_offer)}.
%p You can view the bundle offer under #{link_to @bundle_offer.service.name, service_url(@bundle_offer.service)}.
%em Please note that you can't reply to this message.
unbundle:
%p Dear #{@bundle_offer.service.name} administrator,
%p
  Your bundle offer's (#{offer_full_name(@bundle_offer)}) bundled offer (#{@unbundled_offer_full_name})
  was unbundled.
%p Go to the #{link_to "Offering API", api_docs_url} to verify your bundle offer.
%em Please note that you can't reply to this message.

### PR DESCRIPTION
**Pull request by goreck888**
Change content of messages
regarding to connecting/disconnecting offers
via bundle
Closes #2908

### CODE REVIEW

**Comment by Marcelinna** [comment]
1. Main offer - 100 Percent IT Trusted Cloud > Oferta glowna dla bundla
2. Bundled offer - B2SHARE > For Large datasets
3. Bundle offer - 100 Percent IT Trusted Cloud + B2SHARE > oferta bundlowa

image
in read block should be bundle offer name, now is main offer

**Comment by Marcelinna** [comment]
@agpul @eldenkat We want to change title in mail ?
image

**Comment by eldenkat** [comment]
> 1. Main offer - 100 Percent IT Trusted Cloud > Oferta glowna dla bundla
> 2. Bundled offer - B2SHARE > For Large datasets
> 3. Bundle offer - 100 Percent IT Trusted Cloud + B2SHARE > oferta bundlowa
> 
> image in read block should be bundle offer name, now is main offer

Suitable text: 

Dear bundled offer Provider,
Your offer (bundled offer name) has been incorporated into a unique offer package called bundle along with ……………………..(main offer)
You can see the bundle offer (bundle offer name) at this link ....................................
This is an automatically generated message, please do not reply.

**Comment by eldenkat** [comment]
> 1. Main offer - 100 Percent IT Trusted Cloud > Oferta glowna dla bundla
> 2. Bundled offer - B2SHARE > For Large datasets3
> 3. Bundle offer - 100 Percent IT Trusted Cloud + B2SHARE > oferta bundlowa
> 
> I changed the B2Share service to draft status image
> 
> %p Dear #{@bundle_offer.service.name} Provider, %pThe bundle (#{offer_full_name(@bundle_offer)}) containing your offer (#{offer_full_name(@bundle_offer)}) has been deleted. %p To check its current status please go to #{link_to "Offering API", api_docs_url} %em This is an automatically generated message, please do not reply.

Suitable text:

Dear (Bundled Offer Provider)
The bundle (bundle offer name) containing your offer (bundled offer name) has been deleted.
To check its current status please go to ...........................
This is an automatically generated message, please do not reply.

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
1.I create bundle
image
2.When I try delete offer added to bundle, I see unexpected error
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
1. I create bundle
Main offer - EGI Notebook
Bundled offer - B2drop
2. I change B2drop service status to draft
3. See problem - bundle still exist, email is not sended

**Pull request closed without merging**
