### PR TITLE
Add possibility to filter filter records

### LINKED ISSUE #1088: Add autocomplete for filters
**Is your feature request related to a problem? Please describe.**
Now, some filters have many options and it is hard to find an interesting option.

**Describe the solution you'd like**
As a result of this task, we would like to have autocomplete boxes for filters options like:
- providers,
- research area

**Additional context**
Autocomplete boxes should look like here: 
https://invis.io/24TXHVWEJRG#/384036760_Item_List_Filters_Search_Autocomplete

### PR DESCRIPTION
**Pull request by mkasztelnik**
Fuzzy search is used to filter filter results. The final implementation will be valid for flat and hierarchical multiselect.

Fixes #1088

### CODE REVIEW

**Comment by mkasztelnik** [comment]
@jarekzet, @abacz from a functional point of view this is ready. The only remark is from @abacz side, that filter input should be improved in the CSS. Please deal with this problem, next convert this draft PR to normal PS and assign one technical reviewer and @agpul or @MinLidia.

**Comment by abacz** [comment]
@jarekzet please look at https://projects.invisionapp.com/d/main#/console/15902581/351955222/preview and improve "fuzzy search" inputs. Smaller paddings and add margin below.

**Comment by mkasztelnik** [comment]
Nope, this is wrong - I will fix it.

**Comment by mkasztelnik** [comment]
@agpul fixed, please retest.

**Comment by agpul** [comment]
It works fine for me. But the last question to Andrzej @abacz . Maybe should we apply this functionality also for Related Infrastructures and platforms because we have a lot of them?

**Comment by abacz** [comment]
If it is not complicated, why not?

**Comment by mkasztelnik** [comment]
Search added to Platform filter, @kmarszalek cleanup was done (`console.log` removed - thx).

**Pull request merged**
