### PR TITLE
[#3042] Add dedicated view for bundle 

### LINKED ISSUE #3042: Add dedicated page for bundles (bundle view)
- [ ] As a User when I am on the main page of the service and click on the bundle title I am redirected to the bundle view
- [ ] As a User I can see the dedicated page for bundle according to: https://www.figma.com/file/0FiUXGZWNtRVgzu9ide5fh/Bundle?type=design&node-id=1203-170&mode=design&t=G5uxax3SnTBGlzqw-0
- [ ] As a User I can select the bundle from this dedicated view using the "Select bundle" button (the same behavior like on the service page)
- [ ] As a User I would like to have interactive links in the offers displayed on this page

### PR DESCRIPTION
**Pull request by goreck888**
Add dedicated view for bundle in the mp
Add link to bundle page in bundle title
(on the service page)

/services/:service_id/bundles/:bundle_id

Closes #3042

### CODE REVIEW

**Comment by agpul** [comment]
https://www.figma.com/file/0FiUXGZWNtRVgzu9ide5fh/Bundle?type=design&node-id=1255-380&mode=design&t=83tLZqFnQyUmqky2-4

**Comment by jarekzet** [comment]
Added layout and css mods for this view:
image

**Review by michal-szostak — APPROVED** [review]
I'm giving an approve. Before merge squash repeated commits.

**Comment by agpul** [comment]
New design: https://www.figma.com/file/D2vgx66m1ADdBY0A46NdZ6/Marketplace-EOSC?type=design&node-id=4519%3A5671&mode=design&t=3yTNsoQX44B7Z7kp-1

**Comment by aleksandrahojszyk** [comment]
Screenshot 2023-09-13 at 12 18 15

Screenshot 2023-09-13 at 12 17 38
bez shadow pod details 
sorry jakiś bug się wdał w figmie

**Comment by aleksandrahojszyk** [comment]
jeśłi nie mamy keywordsów to nie pokazujemy słowa keywords

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
Problem with icon 
image

**Comment by Marcelinna** [comment]
parameters from the offer are not visible on bundle page
image

**Comment by Marcelinna** [comment]
The description should be visible
image

**Comment by Marcelinna** [comment]
Make boxes closer according to FIGMA design
image

**Pull request merged**
