### PR TITLE
[#2138] Migrate scientific domains

### PR DESCRIPTION
**Pull request by danielkryska**
[The source documentation](https://confluence.egi.eu/pages/viewpage.action?pageId=64914897#EOSCResourceProfile-ResourceScientificDomain)

- [x] Map all non-permitted domains to Other > Other
- [x] Map all domains without eid that can be moved to it's duplicate with eid
- [x] Delete all domains with empty eid
- [x] create a list of providers/resources emails which will be cast to Other category and pass to @roksanaer
- [x] Remove development domains not consistent with EOSC documentation
- [x] Remove front page application domains not consistent with EOSC documentation
- [x] Send information about changes in the scientific domains to eosc-portal administrators (MS: decided to not sending)

Fetching emails list
---

```SQL
WITH
     domains_ids AS (
       WITH ids AS (
           SELECT id
           FROM scientific_domains
           WHERE name = ANY(ARRAY[
               'Natural Sciences',
               'Engineering & Technology',
               'Medical & Health Sciences',
               'Agricultural Sciences',
               'Social Sciences',
               'Humanities',
               'Generic',
               'Other',
               'Mathematics',
               'Computer & Information Sciences',
               'Physical Sciences',
               'Chemical Sciences',
               'Earth & Related Environmental Sciences',
               'Biological Sciences',
               'Other Natural Sciences',
               'Electrical, Electronic & Information Engineering',
               'Mechanical Engineering',
               'Chemical Engineering',
               'Materials Engineering',
               'Medical Engineering',
               'Environmental Engineering',
               'Environmental Biotechnology',
               'Industrial Biotechnology',
               'Nanotechnology',
               'Other Engineering & Technology Sciences',
               'Basic Medicine',
               'Clinical Medicine',
               'Health Sciences',
               'Medical Biotechnology',
               'Other Medical Sciences',
               'Agriculture, Forestry & Fisheries',
               'Animal & Dairy Sciences',
               'Veterinary Sciences',
               'Agricultural Biotechnology',
               'Other Agricultural Sciences',
               'Psychology',
               'Economics & Business',
               'Educational Sciences',
               'Sociology',
               'Law',
               'Political Sciences',
               'Social & Economic Geography',
               'Media & Communications',
               'Other Social Sciences',
               'History & Archaeology',
               'Languages & Literature',
               'Philosophy, Ethics & Religion',
               'Arts',
               'Other Humanities',
               'Generic',
               'Other',
               'Civil Engineering',
               'Philosophy, ethics and religion',
               'Social sciences',
               'Political sciences',
               'Engineering and Technology',
               'Electrical, electronic and information engineering',
               'Environmental engineering',
               'Medical and Health Sciences',
               'Earth Science',
               'Environmental science',
               'Physical science (earth science)',
               'Economics, Finance & Business',
               'Other Medical Science',
               'Nano-technology'
           ])
        )
        SELECT id
        FROM scientific_domains
        WHERE id NOT IN (SELECT id FROM ids)
     ),
     services_ids AS (
         SELECT DISTINCT service_id AS id
         FROM service_scientific_domains
         WHERE scientific_domain_id IN (SELECT id FROM domains_ids)
     ),
     providers_ids AS (
         SELECT DISTINCT provider_id AS id
         FROM provider_scientific_domains
         WHERE scientific_domain_id IN (SELECT  id FROM domains_ids)
     ),
     services_emails AS (
         SELECT email
         FROM contacts
         WHERE
            type LIKE '%PublicContact%'
            AND contactable_type LIKE '%Service%'
            AND contactable_id IN (SELECT id FROM services_ids)
     ),
     providers_emails AS (
         SELECT email
         FROM contacts
         WHERE
            type LIKE '%PublicContact%'
            AND contactable_type LIKE '%Provider%'
            AND contactable_id IN (SELECT id FROM providers_ids)
     ),
     all_emails AS (
         SELECT * FROM services_emails
         UNION
         SELECT * FROM providers_emails
     )
SELECT DISTINCT email FROM all_emails;
```

Fetch moved objects to specific target category
---
```SQL
WITH
    domains_ids AS (
        SELECT id
        FROM scientific_domains
        WHERE name = ANY(ARRAY[
            'Philosophy, ethics and religion',
            'Social sciences',
            'Political sciences',
            'Engineering and Technology',
            'Electrical, electronic and information engineering',
            'Environmental engineering',
            'Medical and Health Sciences',
            'Earth Science',
            'Environmental science',
            'Physical science (earth science)',
            'Economics, Finance & Business',
            'Other Medical Science',
            'Nano-technology'
            ])
    ),
    services_names AS (
       WITH ids AS (
           SELECT DISTINCT service_id AS id
           FROM service_scientific_domains
           WHERE scientific_domain_id IN (SELECT id FROM domains_ids)
       )
        SELECT concat('(SERVICE) ', name) AS name
        FROM services
        WHERE id in (SELECT id FROM  ids)
    ),
    providers_names AS (
       WITH ids AS (
           SELECT DISTINCT provider_id AS id
           FROM provider_scientific_domains
           WHERE scientific_domain_id IN (SELECT  id FROM domains_ids)
       )
       SELECT concat('(PROVIDER) ', name) AS name
        FROM providers
        WHERE id IN (SELECT id FROM ids)
    ),
    projects_names AS (
        WITH ids AS (
            SELECT DISTINCT project_id AS id
            FROM project_scientific_domains
            WHERE scientific_domain_id IN (SELECT id FROM domains_ids)
        )
        SELECT concat('(PROJECT) ', name) AS name
        FROM projects
        WHERE id IN (SELECT id FROM ids)
    ),
     users_emails AS (
       WITH ids AS (
           SELECT DISTINCT user_id AS id
           FROM user_scientific_domains
           WHERE scientific_domain_id IN (SELECT  id FROM domains_ids)
       )
         SELECT concat('(USER EMAIL) ', email) AS name
         FROM users
         WHERE id IN (SELECT id FROM ids)
     ),
    all_changed AS (
        SELECT * FROM providers_names
        UNION
        SELECT * FROM services_names
        UNION
        SELECT * FROM projects_names
        UNION
        SELECT * FROM users_emails
    )
SELECT * FROM all_changed;
```

UPDATE 
---

Mapping 
`[source domain]: [target_domain]`

'Philosophy, ethics and religion': 'Philosophy, Ethics & Religion',
'Social sciences': 'Social Sciences',
'Political sciences': 'Political Sciences',
'Engineering and Technology': 'Engineering & Technology',
'Electrical, electronic and information engineering': 'Electrical, Electronic & Information Engineering',
'Environmental engineering': 'Environmental Engineering',
'Medical and Health Sciences': 'Medical & Health Sciences',
'Earth Science': 'Earth & Related Environmental Sciences',
'Environmental science': 'Earth & Related Environmental Sciences',
'Physical science (earth science)': 'Earth & Related Environmental Sciences',
'Economics, Finance & Business': 'Economics & Business',
'Other Medical Science': 'Other Medical Sciences',
'Nano-technology': 'Nanotechnology'

### CODE REVIEW

**Comment by Marcelinna** [comment]
<google-sheets-html-origin><style type="text/css"></style>

PC/documentation | MP | Liczba resourcow public w MP (do migracji) |   |   |  
-- | -- | -- | -- | -- | --
**Agricultural Sciences** | **Agricultural Sciences** |   |   |   |  
Agricultural Biotechnology | Agricultural Biotechnology |   |   |   |  
Agriculture, Forestry & Fisheries | Agriculture, Forestry & Fisheries |   |   |   |  
Animal & Dairy Sciences | Animal & Dairy Sciences |   |   |   |  
Other Agricultural Sciences | Other Agricultural Sciences |   |   |   |  
Veterinary Sciences | Veterinary Sciences |   |   |   |  
**Engineering & Technology** | **Engineering & Technology** |   |   |   |  
Chemical Engineering | Chemical Engineering |   |   |   |  
Civil Engineering | Civil Engineering |   |   |   |  
Electrical, Electronic & Information Engineering | Electrical, Electronic & Information Engineering |   |   |   |  
Environmental Biotechnology | Environmental Biotechnology |   |   |   |  
Environmental Engineering | Environmental Engineering |   |   |   |  
Industrial Biotechnology | Industrial Biotechnology |   |   |   |  
Materials Engineering | Materials Engineering |   |   |   |  
Mechanical Engineering | Mechanical Engineering |   |   |   |  
Medical Engineering | Medical Engineering |   |   |   |  
Nanotechnology | _Nano-technology_ |   |   |   |  
Other Engineering & Technology Sciences | Other Engineering & Technology Sciences |   |   |   |  
  | _Aerospace Engineering_ | 0 |   |   |  
  | _Nanotechnology_ | 0 |   |   |  
**Generic** | **Generic** |   |   |   |  
Generic | Generic |   |   |   |  
**Humanities** | **Humanities** |   |   |   |  
Arts | Arts |   |   |   |  
History & Archaeology | History & Archaeology |   |   |   |  
Languages & Literature | Languages & Literature |   |   |   |  
Other Humanities | Other Humanities |   |   |   |  
Philosophy, Ethics & Religion | Philosophy, Ethics & Religion |   |   |   |  
**Medical & Health Sciences** | **Medical & Health Sciences** |   |   |   |  
Basic Medicine | Basic Medicine |   |   |   |  
Clinical Medicine | Clinical Medicine |   |   |   |  
Health Sciences | Health Sciences |   |   |   |  
Medical Biotechnology | Medical Biotechnology |   |   |   |  
Other Medical Sciences | _Other Medical Sciences_ |   |   |   |  
  | _Other Medical Sciences_ | 0 |   |   |  
**Natural Sciences** | **Natural Sciences** |   |   |   |  
Biological Sciences | Biological Sciences |   |   |   |  
Chemical Sciences | Chemical Sciences |   |   |   |  
Computer & Information Sciences | Computer & Information Sciences |   |   |   |  
Earth & Related Environmental Sciences | Earth & Related Environmental Sciences |   |   |   |  
Mathematics | Mathematics |   |   |   |  
Other Natural Sciences | Other Natural Sciences |   |   |   |  
Physical Sciences | Physical Sciences |   |   |   |  
  | _Information Sciences_ | 1 | resource which will be removed by @mszostak |   |  
**Other** | **Other** |   |   |   |  
Other | Other |   |   |   |  
**Social Sciences** | **Social Sciences** |   |   |   |  
Economics & Business | Economics & Business |   |   |   |  
Educational Sciences | Educational Sciences |   |   |   |  
Law | Law |   |   |   |  
Media & Communications | Media & Communications |   |   |   |  
Other Social Sciences | Other Social Sciences |   |   |   |  
Political Sciences | Political Sciences |   |   |   |  
Psychology | Psychology |   |   |   |  
Social & Economic Geography | Social & Economic Geography |   |   |   |  
Sociology | Sociology |   |   |   |  
  | _Economics, Finance & Business_ | 0 |   |   |  
  | **Support Activities** |   |   |   |  
  | _Digital Archives_ | 0 |   |   |  
  | _Infrastructure Development_ | 0 |   |   |  
  | _Miscellaneous_ | 0 |   |   |  
  | _Other Support Activities_ | 0 |   |   |  
  | _Training/Demonstrations_ | 0 |   |   |

**Comment by Marcelinna** [comment]
the table shows that no resource in public status should be migrated to another scientific domain. (this result is expected as users should never be able to add a resourc to an invalid scientific domain that is in MP). There is only one resource that is assigned to Natural Sciences -> Information Sciences. But it will be removed from databases by @mszostak as it is not present on PC

**Comment by Marcelinna** [comment]
For Scientific Domain **Engineering & Technology** should be deleted Aerospace Engineering and Nanotechnology. (See also that in MP we have Nano-technology, Nanotechnology - one thing has to stay and map with Nanotechnlogy in PC, at the moment both have 0 resourcers)

For Scientific Domain **Medical & Health Sciences** should be deleted Other Medical Sciences. (See also that in MP we have Other Medical Sciences, Other Medical Sciences - one thing has to stay and map with Other Medical Sciences in PC, at the moment one has 12 resourcers, other 0)

For Scientific Domain **Natural Sciences** should be deleted Information Sciences.

For Scientific Domain **Social Sciences** should be deleted Economics, Finance & Business.

And All Support Activities should be deleted

**Comment by Marcelinna** [comment]
Providers Production:
image
image

image
image

image
image

image
image


image
image

image
image

image
image

**Comment by danielkryska** [comment]
UPDATE
---

Based on the production dataset we'll cast [source domain]: [target domain]

'Economics, Finance & Business': 'Economics & Business',
'Other Medical Science': 'Other Medical Sciences',
'Nano-technology': 'Nanotechnology'

**Comment by danielkryska** [comment]
@roksanaer emails to which you may want to send information:
andrea.mannocci@isti.cnr.it
alessia.bardi@isti.cnr.it
paolo.manghi@isti.cnr.it
techsupport@openbookpublishers.com
markus.stocker@tib.eu
alessia.bardi@gmail.com

**Comment by danielkryska** [comment]
All Projects, Services, and Providers that will be moved to the Other category:
(PROJECT) AI and Machine Learning 
(PROJECT) AQUASPICE H2020 Project
(PROJECT) AUTHENIX
(PROJECT) BIGcoldTRUCKS_demand_prediction
(PROJECT) Blogs Dashboard
(PROJECT) Bolen's test project
(PROJECT) Chemistry Modeling Prototype test case
(PROJECT) Citizen Science Collaboration
(PROJECT) Comment test
(PROJECT) Comparison of the JupyterHub services in EOSC
(PROJECT) Deep learning based pitch detection for music applications
(PROJECT) Digital Math Test
(PROJECT) EOSC-Synergy
(PROJECT) Handson EOSC
(PROJECT) Industrial Market VDI
(PROJECT) JET
(PROJECT) LICCiA Shift On EOSC
(PROJECT) Master Thesis: Semantic Type Labelling using Deep Learning
(PROJECT) Metadata extraction from text
(PROJECT) My Aerospace engineering  
(PROJECT) New Dice project
(PROJECT) Object detection with geometric sampling and machine learning
(PROJECT) Open charities data 
(PROJECT) OpenBioMaps+
(PROJECT) OpenLab Drilling and Well Simulations
(PROJECT) PIPC
(PROJECT) Pose Dictionary
"(PROJECT) Research Data Management Support for all, incl. Coffee Lectures Research Data Management  (FAIR, EOSC)"
(PROJECT) Scientific Report
(PROJECT) Services
(PROJECT) Simulation of Extensive Air Showers with Deep Neural Networks.
(PROJECT) Softicious
(PROJECT) SurveyMonkey Analysis
(PROJECT) TEST
(PROJECT) Testing robotbenchmark
(PROJECT) Training
(PROJECT) World information resources
(PROJECT) apps
(PROJECT) datasupporttest
(PROJECT) frese2
(PROJECT) happonen-test
(PROJECT) test project
(PROJECT) testProject
(PROJECT) trial access for SLICES-DS
(PROJECT) try apps
(PROVIDER) Leibniz Information Centre for Science and Technology
(PROVIDER) Open Book Publishers
(SERVICE) OpenAIRE Research Graph

**Review by goreck888 — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
You should make migration to Other>Other

**Comment by Marcelinna** [comment]
I would like to check on the PR whether the migration was successful for the Providers, unfortunately I do not see any scientific domains for the Leibniz Information Center for Science and Technology on the PR.
image

Support Acctivite in production should be changed to Other> Other here. Could you use data similar to the production data? so that it can be checked on PR?

**Comment by Marcelinna** [comment]
for me the pr looks ok @kmarszalek I know you started checking PR, so I'm leaving you with a second approve

**Review by kmarszalek — APPROVED** [review]

**Pull request merged**
