### PR TITLE
[#1803] Display sync error for errored resources

### LINKED ISSUE #1803: Display information about sync error on the resource presentation page (provider admin only)
**Is your feature request related to a problem? Please describe.**
Currently we don't give provider admins the possibility to check the PC - UC (MP) sync errors. There is no way for the provider admin to check whether the resource has been successfully propagated to the MP

**Describe the solution you'd like**
A notification on the resource presentation page dedicated for the provider admin when the state is errored. 
On top of the error it'd be good to have the reason of the failure recorded and displayed

**Additional context**
Other roles in the PC should also be able to see the error. Some alignement of the authorisation mechanisms should be considered. Maybe:

 1. Sync of the user roles?
 2. The same session storage?

### PR DESCRIPTION
**Pull request by goreck888**
Change logic, now errored resources
are displayed on resources list
Errors are saved in service_source as errored field.

Fixes #1803

### CODE REVIEW

**Comment by Marcelinna** [comment]
It is ok, I only wonder where the error description should be displayed,
in /services/egi-cloud-compute or /backoffice/services/egi-cloud-compute, because now is  /services/egi-cloud-compute. 

image
image

**Review by Marcelinna — APPROVED** [review]

**Comment by goreck888** [comment]
Added info in the backoffice

**Review by kmarszalek — APPROVED** [review]

**Comment by roksanaer** [comment]
the ideal solution is:
the error appears in /services/egi-cloud-compute for logged in users who have admin role or is associated with the provider underpinned as Resource organsiation.

Of course, displaying this info and error in the backoffice as an addition is totally fine

**Review by roksanaer — CHANGES_REQUESTED** [review]
please see the comment above

**Review by roksanaer — APPROVED** [review]

**Pull request merged**
