### PR TITLE
[#2049] Capybara failing tests

### LINKED ISSUE #2049: Research non-deterministic (random) feature tests (capybara) failures
Currently some feature tests (using JS) fail in a non deterministic way. Current solution is a workaround forcing tests to repeat set number of times until they pass. This solution will not work in the long term.
The end goal of this issue is to find solution for this issue, possible options may include:

* Replace capybara by an alternative
* Replace underlying selenium
* Rewrite falling tests

@danielkryska - If you can please include here which tests are the usual failing ones.

EDIT: @kmarszalek 
https://docs.cyfronet.pl/display/FID/MP+-+Rails+-+Async+JS+Tests

### PR DESCRIPTION
**Pull request by kmarszalek**
remove Repeat from gemfile

https://docs.cyfronet.pl/display/FID/MP+-+Rails+-+Async+JS+Tests

Closes #2049

### CODE REVIEW

**Comment by kmarszalek** [comment]
2) OMS#events returns all events when oms is default
     Failure/Error: expect(default_oms.events[0].eventable).to eq(project1)

       expected: #<Project id: 83, name: "project 146", user_id: 209, reason_for_access: "reason 179", customer_typolo...page207.pl", status: "active", created_at: "2021-06-09 06:26:49", updated_at: "2021-06-09 06:26:49">
            got: #<ProjectItem id: 73, status_type: "created", created_at: "2021-06-09 06:26:49", updated_at: "2021-06...r_required", voucherable: false, internal: true, order_url: "", status: "created", user_secrets: {}>

**Comment by kmarszalek** [comment]
1) Recommender::SimpleRecommender Simple recommender service call with n=1 returns services in the order of the most popular
     Failure/Error: expect(recommended_services_ids).to match_array(most_popular_services_ids)

       expected collection contained:  [592]
       actual collection contained:    [593]
       the missing elements were:      [592]
       the extra elements were:        [593]
     # ./spec/services/recommender/simple_recommender_spec.rb:40:in `block (4 levels) in <top (required)>'

**Comment by kmarszalek** [comment]
1) Favourites As anonymous user I can see checkbox set to true in other view
     Failure/Error: expect(page.find("input#favourite-#{service.id}", visible: false)).to be_checked
       expected `#<Capybara::Node::Element tag="input" path="/HTML/BODY[1]/MAIN[1]/DIV[2]/DIV[1]/DIV[1]/DIV[1]/DIV[2]/DIV[1]/DIV[1]/DIV[4]/SPAN[1]/LABEL[1]/INPUT[1]">.checked?` to return true, got false
     # ./spec/features/favourite_spec.rb:36:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:85:in `block (2 levels) in <top (required)>'

**Comment by kmarszalek** [comment]
Recommender::SimpleRecommender Simple recommender service call with n=1 returns services in the order of the most popular
      Failure/Error: expect(recommended_services_ids).to match_array(most_popular_services_ids)

        expected collection contained:  [593]
        actual collection contained:    [594]
        the missing elements were:      [593]
        the extra elements were:        [594]
      # ./spec/services/recommender/simple_recommender_spec.rb:40:in `block (4 levels) in <top (required)>'

**Comment by kmarszalek** [comment]
1) Api docs page as a regular user My token persists after signing out
     Failure/Error: click_link("Logout", match: :first)

     Capybara::ElementNotFound:
       Unable to find visible link "Logout"
     # ./spec/features/api_docs_spec.rb:91:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:85:in `block (2 levels) in <top (required)>'

**Comment by kmarszalek** [comment]
1) OMS#events returns proper events when oms is not default
     Failure/Error: expect(oms.events[1].eventable).to eq(project_item2)

       expected: #<ProjectItem id: 76, status_type: "created", created_at: "2021-07-06 12:39:10", updated_at: "2021-07...r_required", voucherable: false, internal: true, order_url: "", status: "created", user_secrets: {}>
            got: #<Message id: 47, author_id: 228, message: "text message 40", iid: 0, messageable_type: "ProjectItem"...: false, author_email: nil, author_name: nil, author_role: "user", scope: "public", author_uid: nil>

# ./spec/models/oms_spec.rb:150:in `block (3 levels) in <top (required)>'

**Review by wujuu — APPROVED** [review]

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
