### PR TITLE
feat: [#2878] Change links in the marketplace

### LINKED ISSUE #2878: Change links in the Marketplace
According to the documentation available on Confluence change links in Marketplace:
https://docs.cyfronet.pl/pages/viewpage.action?spaceKey=FID&title=Zamiana+MP+-+%3E+SS

### PR DESCRIPTION
**Pull request by michal-szostak**
@wziajka - `MP_ENABLE_EXTERNAL_SEARCH` should be set to `1`

Closes #2878

### CODE REVIEW

**Comment by Marcelinna** [comment]
Change resources to services 
image
image
image
image
image
image

**Comment by Marcelinna** [comment]
change resource to service in mail 
image

**Comment by Marcelinna** [comment]
- [ ] QA

When I click on Communities and infrastructures and Dedicated for I am redirected to https://search.eosc-portal.eu/search/service?q=*
but filter is not selected

**Comment by Marcelinna** [comment]
When I click on "Add your first service" I see --> 
image
image

When I open in new tab page is correct
https://search.eosc-portal.eu/search/service?q=*

**Comment by Marcelinna** [comment]
- [ ] QA

https://marketplace.eosc-portal.eu/datasources should redirect to datasources in SS

**Comment by Marcelinna** [comment]
still not changed 
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
still not changed
image

**Comment by Marcelinna** [comment]
@michal-szostak button should be removed only when env is set to SS
image

**Comment by Marcelinna** [comment]
still not changed
image

**Comment by Marcelinna** [comment]
still not changed 
image

**Comment by Marcelinna** [comment]
@michal-szostak  when I click on "Add first service", when env  MP_SEARCH_BASE_URL is not set
 MP_SEARCH_BASE_URL
image

**Comment by Marcelinna** [comment]
- [ ] QA

Please change Resource organisation to Service organisation for datasource
image

**Comment by Marcelinna** [comment]
When the env is set and I click on button "Add service to the project"
image
image

**Comment by Marcelinna** [comment]
When the env MP_SEARCH_BASE_URL is set, tags from comparison should redirect to SS All catalogs and turn on filters as in tag in providers and services on details page
image

**Comment by Marcelinna** [comment]
DATASOURCES - When I click on link Geographical Availabilities: 
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
When the user past URL https://marketplace.eosc-portal.eu/target_users should be redirected to SS

**Comment by Marcelinna** [comment]
Please delete this information
image

**Review by Marcelinna — APPROVED** [review]

**Comment by Marcelinna** [comment]
@michal-szostak I have still problem with this 
image

**Comment by Marcelinna** [comment]
@michal-szostak Please make rebase to master again, you have no current changes for e2e

**Review by goreck888 — APPROVED** [review]

**Pull request merged**
