### PR TITLE
[#2338] Fix researching resources from nth page

### PR DESCRIPTION
**Pull request by danielkryska**

### CODE REVIEW

**Comment by Marcelinna** [comment]
I reproduce steps from the linked issue, and I see that problem still exist
image

**Comment by Marcelinna** [comment]
changelog?

**Review by jswk — CHANGES_REQUESTED** [review]
This PR unfortunately doesn't exactly fix #2338, the issue there is rather the behaviour in the backend.

In case the passed page is out of range, then there are several options (all in the backend, not front):
1. return 400 (instead of 500)
2. redirect to an url without the page param
3. show first page (without redirect or modifying the URL)
4. show last page (without redirect or modifying the URL)

Personally, I feel 2. is the way to go. The behaviour will be explicit this way and the user will end up on the first page, which seems logical to me.
What do you think @Marcelinna? (EDIT: We should follow 3. instead. It's how `:page` behaves for negative or non-integer values, so we should keep it consistent.)

(Also please conform to the commit message schema and add appropriate changelog while you're at it.)

**Comment by Marcelinna** [comment]
we should follow with the solution from 3 (show first page)

**Comment by danielkryska** [comment]
Option 2 and 3 are the same (, the missing param is equal to page 1 search). Fixes have been provided with CHANGELOG

**Review by jswk — CHANGES_REQUESTED** [review]
We discussed with @Marcelinna and going for 3. is a more unified way. The option 2. is behaving inconsitently. I.e., if `page=9999` then you get redirected, if `page=-1` you don't.
If you strongly want to do the redirect then do it on other invalid inputs too, e.g. `page=asdf`, `page=.5`, `page=-1`, but probably not for `page=123.12` (as it will be parsed to 123).

For both cases, don't reset the filters when handling the exception. Now the filters are cleared in that case (to see invalid behaviour select a category and then trigger the exception).

**Comment by jswk** [comment]
Also, commit message.

**Comment by danielkryska** [comment]
I got it. Done.

**Review by jswk — CHANGES_REQUESTED** [review]
Works great now, thanks!

Just add the same handling code to `app/controllers/backoffice/services_controller.rb` too, as it still crashes. Sorry I missed it earlier.

**Review by jswk — CHANGES_REQUESTED** [review]
Great that you added the analogous code to the backoffice!

Nevertheless, please revert the changes from #2539 that made their way to this PR.

**Review by jswk — APPROVED** [review]

**Comment by Marcelinna** [comment]
https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/services/c/aggregators-integrators?page=2000
https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/services?scientific_domains[]=1&page=3000
https://marketplace-2.docker-fid.grid.cyf-kr.edu.pl/services?page=2000
image

**Comment by jswk** [comment]
> we handle page=300, but at page=3000 an error has already occurred. Why?

That's why:
```
[cd160567-46f5-458d-83f6-f4dbab0a2b73] Searchkick::InvalidQueryError ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"services_production_20220215101552394","node":"qV2clyRNROeFKWrP4tbt0A","reason":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.","caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}},"status":400}):
```
In particular, Elastic complains:
> Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.

It's a bit different situation that the original problem though. We may limit the page param based on the number of entries in our DB, so this error is avoided until we hit these 10000 entries limit.
But I'm not sure if this is to be handled in this PR.

**Comment by jswk** [comment]
Moreover, this won't manifest in normal browsing situation, as opposed to the #2338. So probably 500 is the right response for this (at least for now).

**Comment by Marcelinna** [comment]
> > we handle page=300, but at page=3000 an error has already occurred. Why?
> 
> That's why:
> 
> ```
> [cd160567-46f5-458d-83f6-f4dbab0a2b73] Searchkick::InvalidQueryError ([400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"services_production_20220215101552394","node":"qV2clyRNROeFKWrP4tbt0A","reason":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}],"caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.","caused_by":{"type":"illegal_argument_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}},"status":400}):
> ```
> 
> In particular, Elastic complains:
> 
> > Result window is too large, from + size must be less than or equal to: [10000] but was [200000]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.
> 
> It's a bit different situation that the original problem though. We may limit the page param based on the number of entries in our DB, so this error is avoided until we hit these 10000 entries limit. But I'm not sure if this is to be handled in this PR.

I think this pr doesn't have to solve this

**Review by kmarszalek — APPROVED** [review]

**Pull request merged**
