### PR TITLE
[#2917] Unlock all offer types in bundles

### LINKED ISSUE #2917: Add the possibility to add all types of offers while creating a bundle
Acceptance criteria:
- [ ]  As a User I want to create a bundle composed of any type of offers for eg.
- one offer is open access and the second offer also is an open access
- one offer is ordered required and the second is an open access
- one offer is ordered and required and the second one also is ordered and required
- [ ]  As a User I can see the status of the bundle on the bundle view as follow:
- if the bundle is made of open access + open access (all offers are open access) display: open access
- if the bundle is made of ordered required + ordered required (all offers are ordered required) display: ordered required
- if at least one offer is ordered required (ordered required+open access) display: ordered required

### PR DESCRIPTION
**Pull request by goreck888**
This PR unlocks all order_types
for the main offer in a bundle,
it means for now e.g. open_access offer
can be chosen as a main offer

Offer workflow changes:
- if an offer is chosen as main_offer in the bundle,
it cannot be destroyed
- removed all associations concerning bundles
in offers and moved relationships to the bundle model

Closes 
  - [x]  #2917, 
  - [x] #2977, 
  - [x] #2973, 
  - [x] #2971
  - [x] #2967
  - [x] #2966

### CODE REVIEW

**Comment by Marcelinna** [comment]
image

**Comment by Marcelinna** [comment]
image
image

I am not able to add offers from the same service to the bundle. I can't bundle two offers from the same service, is that intentional?

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
1. Create new service - service has the first offer
2. Add the second offer and check checkbox  - Bundle exclusive
3. Click button "Access the service"
image

**Comment by Marcelinna** [comment]
When I try delete offer which is main offer in bundle 
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

1. Create bundle 
main offer - ADAM Platform service
bundled offer - Agora Resource Portfolio Management Tool
I see bundle only on  ADAM Platform service page
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Create bundle
1. main offer - ADAM Platform service
2. bundled offer - Agora Resource Portfolio Management Tool
3. Change status  Agora Resource Portfolio Management Tool to draft 
image

**Comment by Marcelinna** [comment]
I create bundle but I can order it

1. Create bundle
2. Main offer - AI-GeoSpecies service (created offer with one parameter)
3. Bundled offer Elastic Cloud Compute Cluster (EC3) - voucher
image

image

**Comment by Marcelinna** [comment]
Please delete the status label from Marketplace, ordering step.
Label should be visible only in back office and ordering configuration page
image

**Comment by Marcelinna** [comment]
When I click on delete button for bundle
image

**Comment by agpul** [comment]
> * [ ]  QA
> * [ ]  DEV
> 
> Create bundle
> 
> 1. main offer - ADAM Platform service
> 2. bundled offer - Agora Resource Portfolio Management Tool
> 3. Change service status  Agora Resource Portfolio Management Tool to draft
> 
> * If the bundled service has been moved to draft status or deleted, the bundle should be removed and an email should be sent to the provider
> * If the bundled service offer has been moved to draft status or deleted, the bundle should be removed and an email should be sent to the provider
>   image
>   image
> 
> @goreck888 Bundle does not delete from the backoffice when service is moved to draft When I delete one offer, the offer is deleted from the bundle, but bundle exist still image

It is good enough, if the bundle offer is drafted we can change the bundle status to draft and the proper email is sent.
Requiremtns:
- [ ]  If the bundled service has been moved to draft status or deleted, the bundle should be drafted and an email should be sent to the provider

**Comment by agpul** [comment]
- [ ] Main offer can't be blocked nad drafted

**Review by agpul — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
change "bundle" to "Bundle" for draft and published buttons

**Comment by Marcelinna** [comment]
1. Create main offer for bundle
2. Create bundle
3. Draft main offer - bundle is drafted too
4. Publish bundle 
5. See problem - it is possible publish bundle if main offer is draft, user should see information that it is not possible publish budle if one of the offers has draft status
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

Create bundle
1. Main offer - European Galaxy Server
 Bundled - LOFAR Science Processing, EGI Data Transfer
image
2. Delete offer - EGI Data Transfer
3. See problem - from the bundle all bundled offer is deleted
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Create bundle 


1. Main offer - ClustVis
2. Cos4Bio - bundle offer 
image
3. Draft offer Cos4Bio
4. See - two offer is visible in bundle (in edit mode field offers is empty)
image
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

1. Create bundle 
**Main offer** - ClustVis
**Bundled offer** - DARIAH-Campus
**Bundled offer** - Cos4Bio 

2. Draft DARIAH-Campus
image
3. Draft Cos4Bio
image
3. See problem - only Cos4Bio is not visible in bundle
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

1. Create bundle
**Main offer** - ClustVis
**Bundled offer** - DARIAH-Campus
**Bundled offer** - Cos4Bio

2. Delete DARIAH-Campus
3. Delete Cos4Bio
4. Bundle has main offer 
image
image

5. Try publish bundle - user can click Publish bundle button and confirm, but bundle is not published (it is ok, but user should see information that should add offer if he want to publish bundle)

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

the view has changed, only the status label should be added
1.Basic view
image
2. Add second offer
image
3. Update first offer

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV

If I remove the offer, it disappears from the bundle, 
if I remove the service, the offer of this service does not disappear from the bundle


1. Create bundle 
Main offer - ADAM Platform
Bundled offer - Service for bundle 21.08.2023 -2
image
2. Delete offer Service for bundle 21.08.2023 -2
3. Offer is deleted from bundle
image


1. Create bundle 
Main offer - ADAM Platform
Bundled offer - Service for bundle 21.08.2023 -2
image
2. Delete service bundle 21.08.2023 -2
3. Offer is not deleted from bundle, is still visible
image

**Review by michal-szostak — APPROVED** [review]

**Pull request merged**
