### PR TITLE
[#2204] Integrate MP with EOSC Commons

### PR DESCRIPTION
**Pull request by wujuu**
NOTES:
- no documentation on how to attach only a ceratin element in the deployed documentation
- no documentation for "onLogin" and "onLogout" in the github README
- header is not responsive and disapears when the width of the viewport is below certain value
- no simple way to add a HTTP method to login and logout URLs (e.g in marketplace the logout is a DELETE request to a certain url) - probably can be done through custom JS onLogin/onLogout but as I understand we are striving for simplicity and minimal configuration
- `body` selector in commons' styles breaks styling in the entire website as all other MP components inherit from it
- header links such as "Catalogue & Marketplace" on development instances don't go to their development instance equivalents (e.g. `localhost:5000`) - instead they navigate to the production instances (e.g. `marketplace.eosc-portal.eu`)
-  in the deployed documentation there is no information on how to attach JS and CSS files

SUGGESTION:
- rename "common" to "commons" everywhere

### CODE REVIEW

**Review by danielkryska — APPROVED** [review]

**Review by danielkryska — APPROVED** [review]

**Comment by Marcelinna** [comment]
image
every elemnet on navbar are bold

**Comment by Marcelinna** [comment]
1. Log in 
2. Go to backoffice
3. Click on Catalogue & Marketplace
4. Why I am redirected to https://marketplace.eosc-portal.eu/ not to https://marketplace-13.docker-fid.grid.cyf-kr.edu.pl/

**Comment by Marcelinna** [comment]
beta
image
PR
image

Services & Resources arent clicable

**Comment by Marcelinna** [comment]
Beta
image
PR - icon is not aligned to text
image

**Comment by Marcelinna** [comment]
new created category isnt added to footer - "new category"
image
image

**Comment by Marcelinna** [comment]
beta
image
PR: lack of yellow underline of active side
image

**Comment by Marcelinna** [comment]
beta
image
PR - another hover for the selected item
image

**Comment by Marcelinna** [comment]
MP
image
Drupal
image


In MP we have **EOSC Doers** which is not included in https://eosc-portal.eu/. I understand that the link should stay? @roksanaer

**Comment by Marcelinna** [comment]
Beta
image

PR - **Past events** should be "Past Events"
image

**Comment by Marcelinna** [comment]
Problem with RWD
image

**Comment by Marcelinna** [comment]
About EOSC Portal is without style css
image

**Review by Marcelinna — APPROVED** [review]

**Review by kmarszalek — APPROVED** [review]
do we want any changelog entry?

**Pull request merged**
