### PR TITLE
Change travis to GH-Actions badge on README.md

### PR DESCRIPTION
**Pull request by kmarszalek**
see readme here. https://github.com/cyfronet-fid/marketplace/tree/read-me

change badge to show gh-action status for Build workflow
added badge for integration test (e2e) workflow

change name for ci.yml, build workflow from CI to Build

### CODE REVIEW

**Comment by danielkryska** [comment]
## Dynamic badges

@bwilk ask me to check dynamic badges, i. e. lines of code. All badge types available at https://shields.io/.

**Setup**
1. Create an account on [Gist](https://gist.github.com/) and get an ID (the long alphanumerical part of the URL)
2. Add Gist ID to https://github.com/settings/tokens with `gist` scope

**Creation steps**
1. Create `github actions` gathering data specific for a certain badge (example https://schneegans.github.io/tutorials/2020/08/16/badges)
2. Generate customized badge on https://shields.io/ (URL that will be placed in README.md)

---
Sources of knowledge:
https://schneegans.github.io/tutorials/2020/08/16/badges
https://shields.io/
https://github.com/marketplace/actions/dynamic-badges

**Comment by danielkryska** [comment]
After a quick talk with @bwilk, we'll like to have [`build badge`](https://shields.io/category/build)

**Comment by danielkryska** [comment]
Duplicated badges in README.md are related to running CI.yml jobs on two actions `push` and `pull request`. @michal-szostak do we need them both? As we use rebase git-flow, they're running simultaneously.

**Comment by kmarszalek** [comment]
> After a quick talk with @bwilk, it'll be nice to have [`build badge`](https://shields.io/category/build)
build badge for the current branch?

> Duplicated `CI` badges in README.md are related to running jobs of CI.yml workflow on two actions `push` and `pull request`. @michal-szostak do we need them both? As we use rebase git-flow, they're running simultaneously. I haven't dig deeper, so my assumptions can be wrong. Please let me know.
duplicate CI badges are from two diff workflows, ci and test.

**Comment by danielkryska** [comment]
When I mention duplicated `CI` I meant two `CI` badges. It was related to @bwilk question about the same called results in the README.md file.
image

**Review by jswk — APPROVED** [review]

**Pull request merged**
