### PR TITLE
New resource presentation page

### PR DESCRIPTION
**Pull request by jarekzet**
In this PR there are modifications of service description page header and some mods in right sidebar according to this view design: https://projects.invisionapp.com/share/G7Y7GWE5FCY#/screens/426517873_Item-Detail_Egi_Cloud_Container_Tabs_About

### CODE REVIEW

**Review by agpul — COMMENTED** [review]
I am adding only comments because I know that the work is in progress and over look is OK:
1.The gaps between these elements should be smaller
image
2.  We should remove the links from the left bar
image
3.  These two fields look different than they should
image

**Comment by jarekzet** [comment]
added sidebar mods with static service classification icons on the top

**Comment by agpul** [comment]
See below inconsistency: 
image

**Comment by jarekzet** [comment]
added classification fix and details tab

**Review by abacz — COMMENTED** [review]
According to https://invis.io/6DY7GVXHCPJ#/426517872_Item-Detail_Amnesia_Tabs_Details
1. 
Screenshot 2020-10-05 at 23 14 06
Arrows should be vertical aligned.

2.
Screenshot 2020-10-05 at 23 14 18
Icons only to describe main categories (like on main page). Below further classification.

3. 
Screenshot 2020-10-05 at 23 14 28
Links should have smaller arrows. Unnecessary dots. 

4.
Screenshot 2020-10-05 at 23 14 40
I suppose that every line is a separate input (?) But can we group like this:

- Agnieszka Pułapa
   a.pulapa@asdas.pl
   manager

One dot 3 inputs (name, mail, ...)

**Comment by agpul** [comment]
This view: 
image has changed. @abacz I think that this is a mistake?
Old view:
image

**Comment by abacz** [comment]
These are same boxes but <li> items have different margins/paddings in it.
Screenshot 2020-10-12 at 08 25 40
Last item should have 0 padding/margin.

**Comment by bwilk** [comment]
merged with https://github.com/cyfronet-fid/marketplace/pull/1641

**Pull request closed without merging**
