### PR TITLE
feat:[#3009] Add limited functionality to offers

### LINKED ISSUE #3009: Add the "vouchers" functionality in Marketplace
Acceptance criteria for Providers:
- [ ] As a provider I receive the email during the deployment of the voucher features into production that we have a new feature (@eldenkat please prepare it)
- [ ] As a Provider I would like to specify the number of available offers using dedicated UI (Figma: @aleksandrahojszyk )
- [ ] As a Provider I have an unlimited number of my offers available as a default
- [ ] As a Provider I receive the email notification with detailed instructions ALWAYS when the number of my offers = 0  (@eldenkat please prepare)

Acceptance criteria for the User:
- [ ] As a user I can see the number of available offers on the offer view (UI: see Figma @aleksandrahojszyk )
- [ ] As a User I can add the offer to the project when the number of offers >0
- [ ] As a user I can't order the offer when the number of available offers = 0 (UI @aleksandrahojszyk )

Additional criteria:
- [ ] The number of offers decrease (-1) when the status of the order = NEW

### PR DESCRIPTION
**Pull request by goreck888**
Add counter for limited offers
Counter is decreasing after add a new project item Closes #3009

### CODE REVIEW

**Comment by Marcelinna** [comment]
Please change the order
image

**Comment by Marcelinna** [comment]
PR
image

Figma
image

**Comment by Marcelinna** [comment]
When the number of offers is greater than 0 - the dot should be green 

PR
image

FIGMA 
image

**Comment by Marcelinna** [comment]
Why we don't have validation on field only on number

image

**Comment by Marcelinna** [comment]
1. Add to project offer with limited access (2 offers) - order required internal
2. I add one offer to the project - I got an email about the order and I see record in JIRA
3. I add second offer to the project - I got an email about the order but I don't see record in JIRA
image

**Comment by Marcelinna** [comment]
- [ ] QA
- [ ] DEV
Change test to ......
image

**Comment by Marcelinna** [comment]
@jarekzet the color should be the same 
image
image

**Comment by Marcelinna** [comment]
@jarekzet please make it a little smaller
image

**Comment by Marcelinna** [comment]
@jarekzet @goreck888 we don't have underlines 
image

**Comment by jarekzet** [comment]
Added mods due to comments:

image
image

**Pull request closed without merging**
